### PR TITLE
Fixes the Vaults protolathe.

### PR DESCRIPTION
**Pull request by JTGSZ**
Gives them the proper protolathe and circuit imprinter

## Description
Wrong ones

## Motivation and Context
Two weeks of complaints

## How Has This Been Tested?
Hosted and tested

### CODE REVIEW

**Comment by Raze500** [comment]
Thanks for everything, sorry for not much.

**Comment by improvedname** [comment]
Thats not the proper autolathe sorry pal

**Comment by improvedname** [comment]
https://github.com/BadDeathclaw/TG-Claw/pull/416

**Comment by JTGSZ** [comment]
Time to get a move on, closing this because I'll do more than just a lazy edit.

**Pull request closed without merging**
