### PR TITLE
Reverts adam's medical changes with small tweaks, Reverts reverts Blood cascade, removes inducers starting with a fully charged power cell, changes two walls in the bos to rough walls

### PR DESCRIPTION
**Pull request by improvedname**
For the chem revert, requested by @RenGusta For the inducer, starts with a high cap battery when printed fully powered, basically free power when you in a powerless situation encourages low RP
Changes two Rwalls in the bos bunker, to rough metal walls to match up with the whole bunker
Reverts Blood cascade as the it was never pushed to server

### CODE REVIEW

**Comment by UndeadNappist** [comment]
but why

**Comment by improvedname** [comment]
@UndeadNappist for the chem ren wanted it

**Comment by UndeadNappist** [comment]
bt y

**Comment by improvedname** [comment]
why what

**Comment by SpaceVampire** [comment]
Good. It turned medicine into just spam Styptic Powder because its instant and everything else takes forever to work. If stacking meds was an issue that should have been fixed instead of just nerfing everything into the ground.

**Comment by DIamonnd** [comment]
Just do waht papa Ren says lmayo libtards

**Comment by Raze500** [comment]
Adam and hyena sitting on a tree K I S S I N G

**Comment by UndeadNappist** [comment]
Keep conversation relevant.

**Comment by improvedname** [comment]
you deleted the best comments

**Pull request merged**
