### PR TITLE
Get Rid of sec borgs

### PR DESCRIPTION
**Pull request by Monika4**
its a borg that can fire disabler with nearly no cooldown and have a stun baton and have a flash and on top of that it can be spammed if enough people is dead. Vault Makes it cancerous because they have the power to just spam sec borg

## Description
Most Annoying thing to fight againist and really abusable by the two tech powers aka BoS and Vault, Mainly Vault
## Motivation and Context
a borg that has rapid firing disabler gun and a stun baton as well as a cuffs so pretty powerful thus annoying because you either need to have EMPs or Ion Rifle (Ion carbine in this case)

### CODE REVIEW

**Comment by JarlElbow** [comment]
Eh, I personally think just removing them isn't a perfect solution, instead of just having them nerfed. 
Since combat robots are a thing that both factions use, even if they currently are a bit OP with how quickly they can fire and stun.
However, security borgs are really the only reason the BoS would make a borg to begin with, and the vault rarely makes anything else, so removing them would practically be like removing borgs altogether for two factions.

**Comment by Monika4** [comment]
its more disabling the Module than removing borgs as a whole

**Comment by imw-Oculus** [comment]
Nerfing is preferable to removal. Some options.
- Increase the energy drain from attacks
- Reduce speed
- Increase cooldown between attacks

**Comment by Monika4** [comment]
yeah I see now that it probly wouldn't be the best Idea but they hard to defeat i'll have a look for attack values or something

**Comment by imw-Oculus** [comment]
Another option would be to reduce their maximum health/armor.

**Comment by Monika4** [comment]
Yeah, that does sound like good ideas oculus

**Comment by GhostEcho** [comment]
The issue is that borgs have no damage slowdown, so even if you reduce their health, they'll just yeet the fuck out of there and get repaired.

There's a reason why secborgs got removed from regular /tg/ and why very little people were upset.

**Comment by GhostEcho** [comment]
Also, if secborgs are the only reason to make borgs, then that sounds like theres an issue with the usability of medical, engi and janiborgs, or the playerbase itself

**Comment by Monika4** [comment]
personnel im sided with Main TG codes idea of yeeting them completey but still it may not be the best idea for this server

**Comment by GhostEcho** [comment]
Really, its the best idea for any server in my opinion

**Comment by imw-Oculus** [comment]
Adding damage slowdown is another option, yes. There are many, many options besides removing them completely.

**Comment by GhostEcho** [comment]
Complete removal is the best though, because seriously secborgs disencourage the use of other modules, and add little to the fun of the game. Also bring back eyebots

**Comment by JarlElbow** [comment]
Well, if we remove sec borgs, I'd like to add in some sort of combat borg/bot that we could use in place of that, since that sort of thing was always so prevalent in Fallout, especially when used by like the Brotherhood and other high-tech factions.

**Comment by EndaruI** [comment]
the fact that they are spamed and out place they sure need a nerf or even removing them literaly some factions depend on this shit

**Comment by Cadwell-Regis** [comment]
GUYS REMEMBER. RND Point Gain, Machines and Mining are being nerfed. So try not to double or triple nerf it just in case it gets fixed.

**Comment by rhicora** [comment]
Sec borgs are a high-octane source of garbage and I've never seen one used in a manner that improves round quality. We'll increase Vault sec slots if we feel security needs are not being adequately met.

Approving this, no merge 'til Ren weighs in.

**Pull request merged**
