### PR TITLE
ERP Fix+New Verb

### PR DESCRIPTION
**Pull request by MrBobCool**
##Description
Fixes some ERP verb typos, and color of text.
Adds the new verb, "Ass Grope/Grope Ass". _Because why not be able to grope someones tits but not their ass?_
**REMOVEDDUE TO REQUEST:**  Adds a 'foundation' for CBT verbs (CBT verbs is a community request. Everyone wishes for it to be locked behind a book, I would continue working on it but I got other things to do.)
Adds some sound to a verb that had no sound.
Made throat fucking do a more oxygen damage.
You can now, bite someones ass on harm intent if they're doing verb;'ass to face'.

##Motivation and Context
Being banned.

That and degeneracy.

I was bored.

##How Has This Been Tested?
Private server, 'cult ghost' dummy.

**NOTE: Don't try to use verbs on the 'Carbon/human/Dummy' or whatever, because the anti-verb spam/cooldown is broken with it for some odd reason.**

##Changelog (neccesary)
🆑
add: Added new things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
code: changed some code
/🆑

http://prntscr.com/oi446u
http://prntscr.com/oi44ch
http://prntscr.com/oi44hq
^Changes made because I don't know how to fix the god damn compare.

### CODE REVIEW

**Comment by MrBobCool** [comment]
Still couldn't fix the weird compare. Use the screenshots.

**Comment by Hekzder** [comment]
If it passes Travis then I'll approve.

**Comment by JohnOxford** [comment]
are you deleting the lewd.dm file and then dragging a dropping a new one with your changes?
are you using github desktop?
are you changing the files in the browser editor?

**Comment by JohnOxford** [comment]
nevermind i looked on my own
its deleting the entire file because thats what you're doing, your manually uploading a new file as opposed to just editing the current file 

bfc82812cf8a37de0658a0033656457f

**Comment by k-k-karma** [comment]
you're underage

**Comment by Hekzder** [comment]
Merge conflicts need to be resolved or this will be closed.

**Pull request closed without merging**
