### PR TITLE
Smooth animations due to fixed server FPS finally

### PR DESCRIPTION
**Pull request by N0B0DY-1MP0R7AN7**
## Description
lowered 40 world.fps default to original 20 fixing animation stuttering.

## Motivation and Context
animations otherwise finished too soon

## How Has This Been Tested?
live tested on server

### CODE REVIEW

**Comment by Raze500** [comment]
F

**Comment by UndeadNappist** [comment]
In which nobody reads the PR nor actually provides and explanation for closure.

Don't do that.

**Comment by improvedname** [comment]
You got your reason in intersice

**Comment by N0B0DY-1MP0R7AN7** [comment]
What... this is my pull request and it fixes a bug that was visible to all players and which i brought to the server owners attention right from the start... why did you close it?

**Pull request closed without merging**
