### PR TITLE
New Legion Explorer Hood

### PR DESCRIPTION
**Pull request by Jackofashepard**
## Description

Added a new legion explorer hood sprite and changed its stats to that of the prime helmet. also added bandannas and glasses to both explorer and scout (it simply looks better)

## Motivation and Context

We were using the cultist hood, this is simply a legion variant that is slightly stronger. Motivation for the buff is that in fallout NV the explorer hood is literally a hood pulled over a prime helmet and the hood having no armour defeats the purpose of the veteren armour the explorer spawns with.

## How Has This Been Tested?
Tested it on a sprite with legion armour as well as actually using it in a server i hosted.

## Changelog (neccesary)
:cl:
add: New Legion explorer hood 
tweak: Both explorer and scout now spawn with bandannas and glasses
balance: Slight buff to explorer hood to match stats of the prime helmet 
/:cl:

### CODE REVIEW

**Comment by Jackofashepard** [comment]
Agh fuck i accidentally dumped it all in the main file, lemme fix this

**Comment by Jackofashepard** [comment]
After MANY edits (my files were outdated) i can safely say this is ready

**Comment by Jackofashepard** [comment]
https://media.discordapp.net/attachments/470357948024225822/590989172123107368/unknown.png

**Comment by Hekzder** [comment]
Merge conflicts and I don't really think this is needed much anymore, initial reception was pretty _meh_ towards the sprite itself and buffing the actual stats of the hood would also be pretty _meh_. Closing this.

**Pull request closed without merging**
