### PR TITLE
Pleasure Bots - The Fourth Pull Request Edition

### PR DESCRIPTION
**Pull request by MrBobCool**
Description
The Pleasure Modules for cyborgs are not so useless now. They come equipped with a USEABLE inventory. Sadly, they can't interact much. I've made it so they can use the interaction drop down menu but they do not have any body parts like a vagina, breast, penis, ect.

The simplemobs being added or the "revamp ERP" hindered most of my abilities. Feel free to find out how to do what I couldn't.

Also, if you are planning to add onto this please note that only borgs can interact with humans while humans can't interact with the borgs. This may or may not be easily changeable. But the interactions are almost useless without the borgs having bodyparts.

Motivation and Context
I opened a issue quite a long time ago and I don't think it'll ever get fixed. #822

How Has This Been Tested?
I tested this on my own private server, tested inside the vault using both the modules on dummies.

Screenshots (if appropriate):
Changelog (neccesary)
🆑
add: Added new things
/🆑

### CODE REVIEW

**Comment by MrBobCool** [comment]
I swear to god Travis.

**Comment by MrBobCool** [comment]
Travis is being big gay someone tell me how to fix him.

**Comment by improvedname** [comment]
Stop using the wr8ng branch lol

**Comment by MrBobCool** [comment]
> Stop using the wr8ng branch lol

Well then tell me how to use the _right_ branch. I'm a noob when it comes to this stuff.

**Pull request closed without merging**
