### PR TITLE
Forgemaster

### PR DESCRIPTION
**Pull request by Light-Weave**
## Description
The Legion now has a forge, which can be used along with a welding tool and materials to create various objects such as machetes, fire axes and throwing spears.

## Motivation and Context
It's awesome.

## How Has This Been Tested?
Yepyep.

## Changelog (neccesary)
:cl:
add: The Legion now has a forge. Stand next to it and open the crafting menu ('Forge' subcategory under 'Tribal').
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
Better leave the katana out because clearly thats gonna encourage catboy weeaboo legionaries

**Comment by companoo** [comment]
i would say to leave katana out aswell

**Comment by Light-Weave** [comment]
Glorious Nippon is now a little less glorious

**Comment by improvedname** [comment]
Im like 50/50 on the combat knife. Altough it woild be great if we go full forge mode. Allow legion to smelt objects back into metal at a bonfire or something. And them use a forge hammer at the forge to craft stuff

**Comment by improvedname** [comment]
Because i don't know how a welding tool makes a perfect combat knife

**Comment by UndeadNappist** [comment]
Allow people to only make replica katanas, which is a different item.

Also sords.

**Pull request merged**
