### PR TITLE
Revert "removes slime permanent rabidity"

### PR DESCRIPTION
**Pull request by improvedname**
ExCuSe me

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
no rage reverts within 24 hours

**Comment by improvedname** [comment]
if you can have 24 hour circlejerk merges i can have within 24 rage reverts

**Comment by AdamElTablawy** [comment]
touche

**Comment by rhicora** [comment]
Explain why a change is appropriate.

**Comment by improvedname** [comment]
Because nappi speedmerging it with zero commication is not appropiate head dev behaviour. Thats the reason.

**Comment by rhicora** [comment]
I agree with that, but this is the part where we finally talk about whether slimes ought to be - or shouldn't be - rabid. I don't want to waffle back and forth on this; make the case for rabidity and we'll weigh it against the original proposal.

**Comment by improvedname** [comment]
The plan. Well my plan as i was adding it to xenobiology, was having it hostile so it wouldnt be easy to stroll out powergear stuff, and then belance around that.

As adam with zero care kicks in and makes the proposal of setting rabid on zero. As it was noob bait he said, i refuse to believe as ss13 is a learning experience you die you learn repeat, adam didnt care for the players and made the pr out of selfish intents and claimed if it didnt get merged he'll pr it to remove it instead.

**Comment by rhicora** [comment]
image

Diam backs this take up, so I'll be reverting the change. 

Let's have a discussion in the future prior to fast merging so that we don't have to do this again. Changes should come with a rationale for why we're making them.

**Comment by AdamElTablawy** [comment]
I was already intending to remove xenobiology regardless, Rhicora.

**Comment by rhicora** [comment]
Great, we can have a balance conversation about it instead of speedmerging it.

**Comment by AdamElTablawy** [comment]
Good. Nappist shouldn't have speedmerged the PR, but you speedmerged this one regardless without pinging me for my take on it until later, so I'm not entirely certain why you did this.

Every point I made in the initial PR was entirely valid.

**Comment by rhicora** [comment]
I merged it after discussion with four other people in a channel you are not privy to.

**Comment by AdamElTablawy** [comment]
Yes, three people who have a bias against me wherein the 'take' was something that failed to address any of the points made, and without actually posting the discussion on the github, where the _specific intent_ of the github comments is to actually debate the point.

Do I need to make a revert revert revert PR about this so that we can have a discussion about it there, too? Or can we continue this here, where I can explain my reasoning in full and you can explain yours.

**Comment by rhicora** [comment]
We can talk wherever.

**Comment by ErwinSnowden** [comment]
Yeah, honestly can we just remove Power armor, chems, and fucking tools? The only reason they're fucking used is because they're in old SS13 and powergamers constantly abuse the fuck out of them, I don't see why the fuck tools are around and building machinery in general as this shit is NEVER seen in actual fallout, especially not on the scale of taking 3 fucking seconds to build a machine. It's not lore friendly at all.

**Comment by rhicora** [comment]
>can we just remove Power Armor
>old SS13

ok

**Comment by rhicora** [comment]
More seriously, tools are used to deconstruct things, screwdrivers are used to tinker with doors and machines, chems are used to operate a functional hospital, etc. We are not removing any of that.

**Comment by ErwinSnowden** [comment]
Yeah, also remove implants, in the games they're either fucking useless and give you brain damage and other shit or they're from the think tank which isn't lore friendly. And by chems I mean turbo, stims, and jet.

**Comment by ErwinSnowden** [comment]
Can we just remove everything from /tg/station and just keep the bare essentials like chatting and switching hands, everything else like combat, speed, and all that needs to be fucking removed.

**Comment by improvedname** [comment]
Can we please not go off topic, of the pr.

**Comment by rhicora** [comment]
Yeah, this is not in good faith. Going to delete the offtopic stuff. Put it in an issue if you are serious.

**Comment by AdamElTablawy** [comment]
Neat then.

The PR was made with the explicit intent that the entire issue is that xenobiology is NOT actually hampered in any way by this.

Ease of xenobiology would be just adding the slime processor back. That's not what I did.

It's still fairly simple and trivial to manage slimes. You need the monkey, or you need rezadone from koibeans, or you can use BZ (safest option). 

All the rabidity PR does is, as I said in the _initial_ revert PR, gatelock xenobiology to powergamers while making it into 'noob bait'-people inexperienced with how to handle a RABID slime will actively end up getting themselves killed by the slimes or destroy all the slimes, because they will start attacking and eating them trying to drag the slimes out of the cage normally.

Without a wiki or any guide books for newer players-or, well, literally anyone aside from three or four people-then xenobiology is not just high risk high reward, it's actually completely impossible to do as they don't know how and will die attempting several times.

Yes, that's entirely part of the learning process, but it's still a bit like if NTSL electrocuted you every time you input the wrong code. It's punishing and unfair, while not actually serving as any risk for anyone who _knows_ what they're doing-it's like the old gutsy or enclave bunkers.

They are going to kill people who didn't know how to handle them-certain chems- on a regular basis, while anyone who did know how to cheese the system would get through them very quickly and without any risk or hassle.

The same property resides here. There is no risk for people who know what they are doing, but there is high reward. It is virtually impossible to foul up on accident but the slimes will kill anyone who doesn't know how to avoid fouling up.

That was the intent of the revert PR.

I _do_ plan on removing xenobiology in full on the grounds of it being disgustingly overpowered and me telling Improvedname about what problems actually existed with it were met with 'idc' and :clap: , so.

**Pull request merged**
