### PR TITLE
Outcasts merge

### PR DESCRIPTION
**Pull request by chowdermcarthor**
Mostly just for another playtest, map should be in a more stable state now.

### CODE REVIEW

**Comment by TheHellFireo** [comment]
Did you fix the drink spawns? Or need me to do it.

**Comment by TheHellFireo** [comment]
Alright, nice. @chowdermcarthor  Update the merge cause ren merged in like 4 PR's

**Comment by TheHellFireo** [comment]
image
The intact enclave base on z2 doesn't have a set ladder for some reason

**Comment by TheHellFireo** [comment]
Also Just replace these with a pre-placed wasteland plants 
image

**Comment by TheHellFireo** [comment]
Might wanna change these fences 
image

**Comment by TheHellFireo** [comment]
Ain't it a bit weird giving vault the priority way to fuck up the entire z2 comms
image

You can grab the items from the display cases.
image

**Comment by TheHellFireo** [comment]
All the wasteland terminals have a button to control the outer door. I think that's for NCR? I'm unsure.
also

HONEY what kind of cutlery do you want. 
Uhh, I don't know maybe the FUCKING PROTO-KINETIC CRUSHER
image
basicly why is that there?

**Comment by TheHellFireo** [comment]
It does not have an access level set. anyone can walk into BoS bunkers ladders.
image

**Comment by chowdermcarthor** [comment]
No merge yet need to fix files.

**Comment by GhostEcho** [comment]
Nice, surely this will work fine

**Comment by chowdermcarthor** [comment]
hol up bruh i had one thing

**Pull request merged**
