### PR TITLE
Explosions will no longer make heat

### PR DESCRIPTION
**Pull request by ma44**
## Description

Explosions will never make turfs heated
## Motivation and Context

Stops atmos lag caused by hotspots, in addition because of all of the lag, hotspots would also make the area constantly do fire damage usually forever
## How Has This Been Tested?

By blowing up things and seeing it doesn't create heat and no excessive atmos lag caused by it

### CODE REVIEW

**Comment by roboticxlink** [comment]
Will this fix thec ground fires not burning out?

**Comment by UndeadNappist** [comment]
Bonfires generate hotspots as well, as do dragonfire shotguns.

**Comment by roboticxlink** [comment]
Bonfires make sense. I haven't seen issues with them too much unless you stand right next to one. But I've had some good rp someone blindfolding me and bringing me next to the fire and could feel the heat in my lungs. I vote to keep hot bonfires if possible.

**Comment by ma44** [comment]
@roboticxlink it won't fix ground fires being burnt out, the desert tiles and outside should filter out the air like lavaland, but if atmos gets big enough then it will take a while to fix things. Sparks also generate heat

**Comment by UndeadNappist** [comment]
Forever or instantly. Burning squares from Dragonfire shells appear to stay burning, but have this weird effect where adjacent squares or squares that had hotspots have messed up kpa and are actually cold.

**Comment by AndrewL97** [comment]
Ill try to do some tests, I think the bug should be fixed in atmos/planetary_atmos, this just stops one of the symptoms

**Comment by UndeadNappist** [comment]
Recent tests with dragonfire shells reveal infinitely burning fires no long occur outside, so this was fixed somewhere along the line. This is now a nonissue except indoors (as it should be).

**Comment by rhicora** [comment]
Since this was last described as a nonissue / something to be fixed in planetary_atmos, I'm going to close it for the moment. Feel free to reopen this if you think it'd be valuable.

**Pull request closed without merging**
