### PR TITLE
Changing Respawn timer to ten minutes

### PR DESCRIPTION
**Pull request by Monika004**
Requested update by ren I believe and requested by Bigfoun.

## Description
Slightly Changing respawn time to 10 minute to make players care more about life or reduce the time shitters can be active

## How Has This Been Tested?
Complied but going to host it and test it

### CODE REVIEW

**Comment by imw-Oculus** [comment]
Let's try 7 minutes to start with, and see how that works. 10 seems a little excessive. If the change is a good one, then we'll bump it up to 10.

**Comment by Monika004** [comment]
yeah man, I just did want I was requested to do but moving it 6 or 7 minutes maybe a start as you said

**Comment by Monika004** [comment]
Changes made

**Comment by JarlElbow** [comment]
+1

**Pull request merged**
