### PR TITLE
cigarettes this one actually works

### PR DESCRIPTION
**Pull request by companoo**
updates cigarettes to real life variants, basically QOL

doesn't change there hierarchies

### CODE REVIEW

**Comment by rhicora** [comment]
This breaks the build, please look into why that is happening.

**Comment by UndeadNappist** [comment]
But it does delete paths or change them, which means that things that may call on them in a list will break. Check what Travis says.
Also remember to compile before submitting.
image

**Comment by companoo** [comment]
not sure how i fucked up cigs

**Comment by companoo** [comment]
fixed the one error that came up

**Comment by UndeadNappist** [comment]
Did you double-check to investigate how the vending machines call on lists so it doesn't runtime every time you try to interact with or spawn a cig vending machine?

**Pull request merged**
