### PR TITLE
Removes plasma cutters, from tech webs, and buffs normal mining drill speed to make it more appealing.

### PR DESCRIPTION
**Pull request by improvedname**
## Description
Removes plasma cutters from techwebs, nerfs the mining range trough rocks

## Motivation and Context
Plasma cutters are lame, and just easy run trough asteroid no effort at all giving BoS good equipment too fast.

## How Has This Been Tested?
simple value changes

### CODE REVIEW

**Comment by DIamonnd** [comment]
Rather than this I'd see the RnD changes that had already been planned be a better solution. But what do I know.

**Comment by improvedname** [comment]
put plasma cutter on dungeon map 👏

**Comment by imw-Oculus** [comment]
Not sure about this one. I'm generally not in favor of removing features. Have you considered making it more expensive/require more plasma per use?

**Comment by improvedname** [comment]
how about i make it use micro cells, and remove the plasma charge

**Comment by Monika004** [comment]
pretty sure plasma cutters was getting removed in RND Passover 2.0

**Comment by imw-Oculus** [comment]
@Monika004 Still retarded.

**Comment by Monika004** [comment]
it do be like that chief, it do be like @imw-Oculus

**Comment by Sanhaven** [comment]
A terrible solution to research, a blatant nerf to both Vault and BoS. Research already takes a lot of time to complete as is, and thats only if the team is half decent at best. It's a medRP server so your not going to get the best team all the time. Most rounds on med pop (47-50) last around 1-1.2 hours on average. Research is fully done around 50-60 minutes in, thats a full damn late game of league ffs. I don't know where everyone thinks BoS can finish research in less than 30 cause thats incredibly incorrect. The only time BoS shines is in actually the late game of the server, and the reason why they dominate is because NCR and Legion have either a.) shot each other, b.) shot themselves, c.) shot BoS while they don't have full strength anymore 1.5 hours into the round. 

There is a already a proposed change to research, but I'd also like to see plasma cutters see more widespead use- maybe add mining camps to where wasters, raiders, and settlers can use it so they can claim materials and use that as bargaining chips. There is so much potential with plasma cutters that the rest of the server can use- so instead of just dumbing down gameplay by nerfing everything ala Overwatch, I'd rather see an addition of content to other roles to provide more diversity. SS13 is unique due to the mechanics it naturally offers, all i've seen from admins these days are just blatant nerfs to quality, unique gameplay from SS13 that the rest of the server can benefit from.

**Comment by JarlElbow** [comment]
You...do realize that all of this is already being added in the R&D update, right? 
Like, literally everything you put here is already being changed.

**Comment by improvedname** [comment]
Be quicck

**Pull request closed without merging**
