### PR TITLE
Replaces plasma for coal in almost everything related to mining and research.

### PR DESCRIPTION
**Pull request by GoodG1448**
Plasma isn't lore friendly to fallout. All files related to plasma will remain in the code, this means that players will no longer have means of obtaining it but admins will be still able to spawn sheets/ore.

Coal/Plastic will be common as plasma and give pretty much the same ORM points as plasma did, mind that they have the same material requirement ammount for designs that once required plasma.

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
1. We use plasma for chemistry recipes too

2. We don't really care about lore

3. Doesn't make sense anyway

**Comment by GoodG1448** [comment]
> 1. We use plasma for chemistry recipes too
> 2. We don't really care about lore
> 3. Doesn't make sense anyway

1. Only for situational medicine like clonexadone/cryoxadone, lepozarine, happiness, miner's salve (lol who even uses this) and two shitty poison reactions. Cryo tubes aren't avaiable at all, only cold showers might work with clone/cryo. Not a big game changer for medical roles at all if you ask me. If that would be the case, it could be easily solved by leaving a beaker with 30 units of plasma at the Kebab/BoS/NCR's clinics. 

2. Coal doesn't have a big part in the fallout universe, I'll give you that, but it just fits the setting better than a snowflake space fuel/mineral. Also, the fact that it can be used to render areas stained with poisonous air permanently sucks dick.

3. I take you mean by turning coal into plastic, from simple google search: 

> Plastics are derived from natural, organic materials such as cellulose, **_coal_**, natural gas, salt and, of course, crude oil.

Sure, throwing coal into a machine and shitting plastic from the other side might not look as complex or beliveable. But even that has a lot more sense than throwing a highly flammable and volatile purple material into a furnace and shitting out fuel sheets from it. The ORM is quite a bullshit processing machine tbh.

**Comment by JohnOxford** [comment]
@AdamElTablawy shit man really insightful you sure systematically broke apart and analyzed why this PR shouldn't happen damn dude your a absolute legend imagine being that correct about something wow

Screen_Shot_2018-10-25_at_11 02 15_AM

**Comment by AdamElTablawy** [comment]
doesn't make sense in the sense that plastic sheets already exist, you moron, it's makeable by chemistry, you've just doubled up on the same thing

**Comment by JohnOxford** [comment]
lol

**Comment by JohnOxford** [comment]
#246

**Comment by Hekzder** [comment]
Really old and continuously failing Travis, can be re-opened after more discussion, maybe. But I really don't think this is needed, there is a reason it hasn't been merged in almost a month.

**Pull request closed without merging**
