### PR TITLE
Ammo crafting bench

### PR DESCRIPTION
**Pull request by imw-Oculus**
## Description
- Adds reloading bench
- Cleans up some projectile files
- Changes some damage values (INPUT REQUIRED)
- Adds blackpowder to junk loot spawns
- Changes what ammo the Rangemaster uses

## How Has This Been Tested?
Tested with 10mm ammo -> 10mm hollow-point ammo

### CODE REVIEW

**Comment by Monika4** [comment]
Finally Reloading my bullets is here other than shoving them in the autolathe

**Comment by imw-Oculus** [comment]
Map isn't compiling for some reason. Any thoughts would be nice, but I'm done with this for the day. Whew.

**Comment by imw-Oculus** [comment]
I lied. Just did the final test, everything works fine. All I need now is feedback on damage values.

**Comment by Monika4** [comment]
Damage looks fine. but some ammo types namely needles pen should be changed because needles shouldn't really be able to have the force behind it to get through Body Amour. im gonna check it in a live review other than just look at it

**Comment by Raze500** [comment]
### You can do it!

**Comment by JohnOxford** [comment]
you can categorize damage and shells into the following

extra small bullet (.22lr/380.) = 7+ shots to crit
small bullet (9mm/10mm/) 6 shots to crit 
below average bullet (45. ACP/357) 5 shots to crit
average bullet (5.56/44-mag/7.62x32r (nagant) (laser weaponry)) 4 shots to crit
above average bullet (7.62/308/45-70(plasma weaponry)) 3 shots to crit
thicc bullet (50. BMG/propritary 5.7 cartridges) 2 shots to crit
dumb thicc bullet (50. BMG AP/Soph/railgun/gauss rifle) 1 shot to crit
stupid shit = blows limbs off, destroys walls, collapses mountains (45. ACP AP)

**Comment by GhostEcho** [comment]
Re open if you ever get back to this

**Pull request closed without merging**
