### PR TITLE
Stimpak changes

### PR DESCRIPTION
**Pull request by improvedname**
## Description
Makes stimpaks inject in 5 units it will heal around 30 brute damage, one full stimpak will cover your whole health bar theres a slight delay on injections like a notable 0.5 deciseconds, so you can't completly rely on it in combat for a 30+ heal

## Motivation and Context
Because stimpaks are severly weak then healing powder. this will make them more useful on quote a quote with healing powder. but not something you can rely on

## How Has This Been Tested?
Sprites worked, tested ingame. around a 30 heal in a 5 unit injection

## Changelog (neccesary)
:cl: Improvedname
balance: Metabolism has been changed for stimpaks from 3 to 1.5
imageadd: added some stimpak state icons, and replaces the old draw/inject overlay for normal syringes
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
@UndeadNappist This is our different approaches on the stimpak thing, this is just an alternative really

**Comment by UndeadNappist** [comment]
Discussed issues and why stimpaks are mechanically being left as-is. I do like having new sprites, though.

**Comment by LetterN** [comment]
i approve of slow metab, it will make it so it isn't fucking instant heal

**Comment by ChronicPwnage** [comment]
> 
> 
> i approve of slow metab, it will make it so it isn't fucking instant heal
> 
> though nappist was right about the od, overdose is 20

Most discussion on discord has tended towards stimpack = fast moderate heal, healing powder = slower large heal. There should be differentiation.

**Comment by GhostEcho** [comment]
New proposal up, this hasnt been worked on in awhile

**Pull request closed without merging**
