### PR TITLE
Adds Vault 223 (Russian Vault) (Gulag's Electric Boongaloo 2)

### PR DESCRIPTION
**Pull request by Aidano2009**
Adds an explorable vault,it contains normal gear but many enemies.It could be used as a base or some shit if you got the tools to repair most of it.

It has been tested several times to "Balance" Weapon spawns and etc (I swear to god i dont want to deal with Mentats forever).

Screenshots (Demanded): 

 Main Hallway

 Security

 Main Storage

 Garden (Botanist area)

 Enginieering (At least part of it)

 Medbay

### CODE REVIEW

**Comment by Kimochiiiiiiiiiiiiii** [comment]
Literally what we needed. the vault we have in the map right now is only used by ERP-focused nerds that escape from it without being in unrepairable conditions

### But fuck vault tho, who needs 'em anayway, it's cancer.

**Comment by ErwinSnowden** [comment]
> Literally what we needed. the vault we have in the map right now is only used by ERP-focused nerds that escape from it without being in unrepairable conditions
> 
> ### But fuck vault tho, who needs 'em anayway, it's cancer.

If you hate ERP so much why don't you remove it. Yeah that's what I thought. This is an ERP community and if you don't like it maybe you should just learn to code.

**Comment by UndeadNappist** [comment]
Could we get some screenshots?

**Comment by Kimochiiiiiiiiiiiiii** [comment]
Lovin it when cunts like ErwinSnowden comment shit defending ERP and then delete their message right away.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
We did it Boys, PR merged.

**Pull request merged**
