### PR TITLE
Healing poultice is gone.

### PR DESCRIPTION
**Pull request by AdamElTablawy**
I just wanted to remove the damage slowdown from the legion med-x and replace it with something else, but hey ho, away it goes

### CODE REVIEW

**Comment by SpaceVampire** [comment]
I'm going to assume this is mostly a joke, because its such a zero effort solution, it should not be merged. There are better ways to balance then just removing stuff, and between the fact that heal stacking is gone, and you can't use more then one in a row without ODing, its not that strong. I would also like to see how the slowdown changes we have in the works effect balance before doing something like this.

**Comment by AdamElTablawy** [comment]
It's not a joke.

No feedback is being considered.

Thanks.

**Comment by JohnOxford** [comment]
it didnt pass travis

-closes your pr-

**Comment by JohnOxford** [comment]
nothing personnel kid

**Comment by JohnOxford** [comment]
truth is,












travis was rigged from the start





- shoots you with maria -

**Comment by SpaceVampire** [comment]
Truth is, this PR was rigged from the start.

**Comment by JohnOxford** [comment]
from where your pr'ing, looks like you had a ten commit run of bad luck

**Comment by JohnOxford** [comment]
patrolling adam's pr's almosts make you wish for a nuclear winter

**Comment by ryai11** [comment]
omg. stop.

**Comment by AdamElTablawy** [comment]
this is the most you have ever contributed to the server, oxford

thank you for your comedy it's almost as funny as your usual arguments

**Comment by JohnOxford** [comment]
adam your literally the punching bag of the codebase

except the punching bag requires the approval of anyone besides themselves to exist

wewlad

**Comment by AdamElTablawy** [comment]
ok thanks oxford

**Comment by JohnOxford** [comment]
you are welcome

**Comment by JohnOxford** [comment]
they asked adam if he had a degree in theoretical bad pr making. he said he had a degree in theoretical bad prs

**Comment by Hekzder** [comment]
After some discussion, this PR will most likely not be needed. Poultice will get it's nerf eventually.

**Pull request closed without merging**
