### PR TITLE
NCR Slight Base Changes 2.0

### PR DESCRIPTION
**Pull request by Hekzder**
## Description
Since Brahmin are a no-go, NCR base still has too many pens and they still need buckshot since they no longer have ANY .45 weapons. Also makes it so the exterior of the NCR base is counted as Desert tiles.

## Motivation and Context
Captain is getting their M1911 removed soon, so NCR has no .45 weapons. With Heavies being added, NCR now has 4 shotguns, which makes buckshot make a lot more sense. The area designation changes with the tiles are mainly for the eventual addition of weather, things like sandstorms. 

## How Has This Been Tested?
Not tested super extensively, but it is a very small mapping change so it shouldn't be a super big issue. 

## Changelog (neccesary)
:cl:

del: Removed excess pens from NCR base.

tweak: Replaces the 4 .45 ammo boxes in NCR armory with 4 buckshot boxes.

tweak: Replaces the area designation of the NCR main base exterior from NCR Main Base to Desert.

/:cl:

### CODE REVIEW

**Comment by Light-Weave** [comment]
Toss in a few broc and xander seeds for farming- with the chem rework, NCR has zero sustainable meds without both a Med Officer *and* a scavenged dispenser.

**Comment by Hekzder** [comment]
> Toss in a few broc and xander seeds for farming- with the chem rework, NCR has zero sustainable meds without both a Med Officer _and_ a scavenged dispenser.

_Ehhhhhh_ I understand the reasoning behind it but I don't think it's an unreasonable expectation for NCR to get a dispenser and a Med Officer. Alternatively, it will encourage them to interact with Den and try to get a medical trade set up with them until they get a Med Officer. 

Overall, the lack of healing powder creation, while it may be rough for NCR early game, should result in more RP interaction between Den and NCR aside from just "We help against Legion, you help against Legion, yes???"

**Comment by Light-Weave** [comment]
True, yeah. I would like to see some more DenCR alliances.

**Comment by Hekzder** [comment]
Changed into 3.0 to avoid merge conflicts.

**Pull request closed without merging**
