### PR TITLE
[UPDATE] Medical crafting

### PR DESCRIPTION
**Pull request by Raze500**
Adds more recipes for the medical category

### CODE REVIEW

**Comment by UndeadNappist** [comment]
No large or extra large beakers unless you recode grenades to only accept small beakers.

**Comment by Raze500** [comment]
Re-Coding Grenades just to use a small beaker is very stupid, also even with extra largue beakers even in a example... You add 300u water/pot and make a grenade with that, it will just make a explotion of 100u of water/pot... 

Changing almost all a code for nerfing a grenade sounds a waste of time for me.

**Comment by UndeadNappist** [comment]
And if you code the grenades to only use 50u beakers, that won't be a problem.

**Comment by imw-Oculus** [comment]
I feel this was closed a little hastily. Asking him to reopen so we can discuss.

**Pull request closed without merging**
