### PR TITLE
Stock part fix

### PR DESCRIPTION
**Pull request by roboticxlink**
Fixes stock part level values.

### CODE REVIEW

**Comment by roboticxlink** [comment]
But fuck my master branch is messed up rn and can't figure out how to fix it on mobile...

**Comment by LetterN** [comment]
test this on other stuff, see if it breaks autolathes, ORM, protolathes, etc...

**Comment by roboticxlink** [comment]
#215 I believe someone commented with the tests on those. But I'd ask what else they changed when they changed it to powers of 2.

**Comment by ma44** [comment]
@roboticxlink about all of the rnd machinery had it's efficiency based on stock parts changed as well as the autolathe and mecha fabricator

**Comment by roboticxlink** [comment]
Ugh WHHHYYYY?!! Who would do such a thing? D:

**Pull request merged**
