### PR TITLE
Iron Fist trait

### PR DESCRIPTION
**Pull request by imw-Oculus**
## Description
This trait raises the minimum damage of punches to 2, and the maximum to 10. This gives people the ability to knock others over with a punch, and overall increases the effectiveness of unarmed combat. Costs three points.

## How Has This Been Tested?
Tested on private server, functions as intended.

### CODE REVIEW

**Comment by imw-Oculus** [comment]
Running fine now. Stupid mistake.

**Comment by AndrewL97** [comment]
@imw-Oculus fix conflicts you egg

**Comment by imw-Oculus** [comment]
Conflict resolved.

**Comment by imw-Oculus** [comment]
Fuck. I'll fix this tomorrow.

**Comment by imw-Oculus** [comment]
It wasn't my fault for a change! Yay!

**Pull request merged**
