### PR TITLE
Vault Update

### PR DESCRIPTION
**Pull request by brobra1**
## Description
Adds vault to the current map and re-enables vaultie roles. Vault is limited on food and uranium and will have to eventually send an expedition party to obtain more supplies and keep the vault functional.

## Motivation and Context
Takes full use of vault assets with the redesigned vault and makes them a more traditional faction.

## How Has This Been Tested?
Vault has been compiled and tested multiple times for its various features.

## Changelog (neccesary)
:cl:
add: Redesigned vault
add: Gravity generator near Telecoms since vault can't function without it
tweak: Slimes now only give one extract.
tweak: modified overseer wardrobe
/:cl:
## Screenshots:
Screenshot (72)
Screenshot (73)

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
I want to raise a point that slime xenobiology can be cheated to bypass your reasoning of ``Vault is limited on food and uranium`` if you fed live vault member/outsider humans to the slime to cause division, then harvested monkeys with mega efficiency of 3 cores per 1 slime.

Along with other unbalanced slime mutations with even more powerful effects are still in when the grey slimes evolve ([slime types](https://github.com/BadDeathclaw/TG-Claw/blob/c21f8be93a0292c70be0855d61d0824ef85cb3b7/code/modules/reagents/chemistry/recipes/slime_extracts.dm) & [slime child mutations intact](https://github.com/BadDeathclaw/TG-Claw/blob/d6ffeb207849abcc3d993d4326ee0cef6c9c1a73/code/modules/mob/living/simple_animal/slime/powers.dm#L156))

**Comment by brobra1** [comment]
Xeno biology was nerfed for f13 in this update https://github.com/BadDeathclaw/TG-Claw/pull/513/files#diff-30c7d7442ca607ef5de23cef81d50298R41. Slimes now yield one slime per surgery and should be balance for the vault setting.

**Comment by brobra1** [comment]
Slimes now grant only one core when harvested via surgery.

**Comment by AdamElTablawy** [comment]
crossbreeding means that this still doesn't mean anything atm

also, when you say limited on food and uranium, that's because there is no mine, correct?

that also means that r&D cannot actually make anything requiring minerals.

**Comment by brobra1** [comment]
R&D was removed. Vault does not have direct access to a mine.

**Comment by brobra1** [comment]
Sealed off the vault with dense rock and disabled vault roles. Vault can be added without effecting the server and allowing others to edit it.

**Comment by Hekzder** [comment]
PR was mostly abandoned by the original creator, Vault debate is still raging on with no conclusion in sight, and this PR will continue to constantly have merge conflicts.

**Pull request closed without merging**
