### PR TITLE
Adds a crashed alien spaceship to the deathclaw dungeon

### PR DESCRIPTION
**Pull request by ErwinSnowden**
*puts on tinfoil hat*

aliums are now real you gotta find them in valiant combat it's the hardest mission you'll ever take.

Deathclaw mountain now has a crashed alien ship because aliens are canon because fallout 3 :sunglasses:

first mapping PR so i may have completely shit the bed here. give me any tips and request changes where changes are due.

## Description
oh yeah so i copy and pasted a lavaland ruin and then i changed it by adding random ore rocks and adding nudges to actual fallout content by renaming the alien pistol and changing the damage on the shockbaton contained inside the crashed ship.

## Motivation and Context
There's a lack of motivation of actually going to the deathclaw mountain, nobody is interested in it except the brotherhood, rarely. This gives you more reason to go explore and test your skill in the mountain as it is a bit deep in.

## How Has This Been Tested?
i didn't test it because i'm a lazy shitter and i dont want to fight 600 deathclaws just to mine a tiny area of the map.
this only effects centcom.dm and no other z-levels, in the future I will hopefully add more content to the deathclaw mountain such as a red chinese operations bunker which will have ghoulified chinese sleeper agents, it will be similar to the syndicate lavaland base, which will have varying loot in it including the ~~platinum chip~~ coveted combat software upgrade, an experimental disk that can be inserted into AIs. I don't think the vault will ever directly get their hands on this in an AI round so it's pretty niche and as rare as it would be to win the lottery. If it does become an issue, nerf the abilities of combat upgrade.

## Screenshots (if appropriate): 
westvirginia

### CODE REVIEW

**Comment by improvedname** [comment]
Pictures

**Comment by ErwinSnowden** [comment]
shit

**Comment by AdamElTablawy** [comment]
what's the point of this when alien tools and stuff are already available through r&D

also side note abductor random event when

**Comment by ErwinSnowden** [comment]
> what's the point of this when alien tools and stuff are already available through r&D
> 
> also side note abductor random event when

abductor body could lead to some rare lategame RP along with the technology, maybe we should just remove advanced technology from RnD

when you code it, events need to be stripped down, like breaking lights or appendicitis(?) and the abductor console needs infinite vision instead of just cameras so it cant only beam down to raider mall

**Comment by ErwinSnowden** [comment]
oh and im going to add a special chance for something special to spawn in it nya~

**Comment by UndeadNappist** [comment]
I have no idea how to respond to this and we've gone/will go through a few map changes, so it's probably not gonna be happy to merge.

**Comment by improvedname** [comment]
Low tier copypaste, comeback when you mapped something more interesting

**Pull request closed without merging**
