### PR TITLE
updates brotherhood slots

### PR DESCRIPTION
**Pull request by companoo**
1 knight slot
1 scribe slot
two knight initiates
two scribe initiates

### CODE REVIEW

**Comment by UndeadNappist** [comment]
Can we hold off on any more job changes for a bit?

**Comment by skateboardjones** [comment]
first round that i played bos had some pretty good players, but opening up more job slots will just attract more idiots imo.

**Comment by rhicora** [comment]
Code is fine, balance subject to Ren's approval.

**Comment by RenGusta** [comment]
Not keen to expand the faction past what it is. Paladin, Knight, Head Scribe, Two Scribes, and Two of Initiate Knight, one of Initiate Scribe was the posed balance, and the only reason I agreed in the first place. Firm no from me.

**Pull request closed without merging**
