### PR TITLE
Adds changelog to pull request template

### PR DESCRIPTION
**Pull request by improvedname**
You'll see this makes the ingame changelog work so theres no longer need for the dev-announcements

### CODE REVIEW

**Comment by UndeadNappist** [comment]
After all roles are moved over and the transition period is smoothed out, all old roles are supposed to be deleted unless someone wishes to keep them for historical reasons.

The exceptions are Three Dog (it's already fallout), Host (I believe it plugs into other stuff so removing it would cause problems) and possibly admin (for the same reason).

I referenced this in the previous PR when warning John not to delete roles people were currently configured to because it would lead to headaches and problems.

**Comment by improvedname** [comment]
Wrong PR nappist...

**Comment by rhicora** [comment]
This seems like a good change, though some players may still want it in #dev-announcements. Thoughts on this @UndeadNappist ?

**Comment by improvedname** [comment]
You can have both it doesn't hurt, it visualizes the PR in short, adds a update changelog in the game, and you can still to dev-announcements if you really want to.

**Comment by Autismobirb** [comment]
Seems fine to me, Keeping #dev-announcements so head scribes can give there flare to it and annoy the ping whores.

**Comment by improvedname** [comment]
https://cdn.discordapp.com/attachments/470355438572011530/560532469699575848/unknown.png
image

**Comment by JohnOxford** [comment]
A valid plan would be to have development annoucements become the github bot's channel, as opposed to it being coding-public

then to merge this

**Comment by GhostEcho** [comment]
Well part of dev announcements seems to be fun memery, though having a github bot channel would be nice, rather than it being in coding public

**Pull request merged**
