### PR TITLE
Civilian Clothing

### PR DESCRIPTION
**Pull request by Cw3040**
-Mapmerge isn't working right send help
-adds civilian clothing vendor to BoS base, with a variety of clothes

:cl:
add: adds civilian clothes vendor to BoS base
/:cl:

### CODE REVIEW

**Comment by Light-Weave** [comment]
mapmerger is fine you just need to run tgm2dmm before committing

**Comment by RenGusta** [comment]
They're not getting a vendor full of conspicuous and obvious clothing. They should get a pile of random f13 outfits, and shoes.

**Comment by Light-Weave** [comment]
It already has random f13 outfits (and only gets conspicuous, obvious ones when hacked), this is a custom BOS vendor. Does need shoes, though.

**Comment by Cw3040** [comment]
Will add some black sneakers (5x)

**Comment by Cw3040** [comment]
Just added black sneakers (5x)

**Comment by Light-Weave** [comment]
1) prepare maps.bat
2) make changes
3) mapmerge.bat
4) tgm2dmm.bat
5) commit

**Comment by Cw3040** [comment]
I did that, diff was still ~85k

**Comment by Light-Weave** [comment]
did you mapmerge boxstation or centcom? BOS is centcom so

**Comment by Cw3040** [comment]
Centcom, which is #5 on the list

**Comment by Light-Weave** [comment]
if you revert the changes to the actual map file and just PR the vendor, it can get speedmerged and we can try adding it in with a new PR with the map merger working

**Comment by Cw3040** [comment]
Will do when I get the chance

**Comment by Cw3040** [comment]
Closing this PR to make a new one with no map changes

**Pull request closed without merging**
