### PR TITLE
Memes

### PR DESCRIPTION
**Pull request by UndeadNappist**
I regret nothing.

(Adds some more hats to normal raider role)

### CODE REVIEW

**Comment by LetterN** [comment]
tbh just sell hats

**Comment by AndrewL97** [comment]
What are we doing committing large swaths of commented code?

**Comment by UndeadNappist** [comment]
It's a joke job role and equipment set. I can enable it if you want, but I was mostly messing around because it made me laugh.

It's raider with cursed items and straight jackets, etcetra.

**Comment by AndrewL97** [comment]
Fair enough,
can we try, in future, to avoid committing large commented out code though? Its not even something an Admin could enable in game for laughs.

**Comment by UndeadNappist** [comment]
I'll un-comment it in #235

**Pull request merged**
