### PR TITLE
Makes patrol rangers look mildly better.

### PR DESCRIPTION
**Pull request by pireamaineach**
[Deep] brown armour gross and yuck.

I'd say the various sizes are based on importance but really it's just that I changed the way I got the images throughout the process of making this.
New boy:
pleaseren
ReconNewHatNewDuster
NewHatNewCoat
NewRangerNewCoatSide

:cl:
add: Added patrol ranger underclothes.
add: Added patrol ranger gloves.
tweak: Made the patrol ranger armour look less yuck.
tweak: Made the ranger hat lighter coloured.
tweak: Made the recon ranger coat match the new hat's colour, and added the ability to toggle the collar.
tweak: Patrol rangers now spawn with laced boots instead of work boots, patrol ranger gloves instead of fingerless gloves, and a patrol ranger uniform instead of a ranger uniform.
balance: Patrol rangers now spawn with N.C.R. duty belts.
/:cl:

### CODE REVIEW

**Comment by pireamaineach** [comment]
Did something fucky to the cowboy uniform it seems. Let me fix that.

**Comment by RenGusta** [comment]
Dude whoa this does not fit the aesthetic. Have you not played NV and seen their brown armor?

I'm fine with it being changed, but I don't think I'm fine with it looking like this.

**Comment by pireamaineach** [comment]
This is far more accurate to patrol ranger armour than the current armour though.

The armour is tan mate.

**Comment by pireamaineach** [comment]
RangerNewNotTanPleaseDontLynchMeRenJesusFuckingChrist

**Comment by pireamaineach** [comment]
@RenGusta

**Comment by pireamaineach** [comment]
How are there merge conflicts for a map file I didn't even edit a map file.

**Comment by pireamaineach** [comment]
Wait it's just that the map bot shits itself on any merge conflict. Weird.

**Comment by pireamaineach** [comment]
GOD IS GOOD

**Pull request merged**
