### PR TITLE
Re-adds ERP

### PR DESCRIPTION
**Pull request by JohnOxford**
Reverts BadDeathclaw/TG-Claw#779

-long winded and existential discussion referencing to the previous PR saying how removing ERP is bad and how removing it was a joke not a feature, its april 9th not april 1st)

### CODE REVIEW

**Comment by GhostEcho** [comment]
Had a serious staff discussion about it and decided we're going to try out a removal of ERP verbs for now

**Comment by GhostEcho** [comment]
Alright this is becoming autistic and I dont care anymore

**Comment by JohnOxford** [comment]
no im okay, dont think this is up to BD's coding standards ;)

**Comment by JohnOxford** [comment]
don't think you heard me correctly

**Pull request closed without merging**
