### PR TITLE
Great Khans + Parish & map edits

### PR DESCRIPTION
**Pull request by Arkatos1**
## Description

This combined PR has two parts:

1) Introducing.. Great Khans! Pushers were transformed into Great Khans, with the Chicken Ranch brothel as their base of operations and improved loadout. Gang system was updated to accomodate for them, and they have unique version of their gangtool, allowing them use gang influence to buy Great Khan specific gear!

2) The second part is the following PR: https://github.com/BadDeathclaw/TG-Claw/pull/1313 by @Thescri and @John-Dang! Includes revamped Parish and some map tweaks and fixes.

Also contains some other minor fixes and tweaks, like making BoS base picker indestructible and not being able to be disassmbled or some tweaks to the elevators.

## Motivation and Context

Great Khans gang and better map.

## How Has This Been Tested?

Locally tested without any issue.

## Changelog (neccesary)
:cl: Arkatos, Thescri and John-Dang
add: Great Khans + Parish & map edits
/:cl:

### CODE REVIEW

**Comment by Kabramen** [comment]
>making the brothel into a functional base
Might as well make a escort role to, ahem, help the Khans with business.

**Comment by John-Dang** [comment]
I did the parish bit! The rest looks great too!

**Comment by TMR-SS13** [comment]
Could we get a picture of Chicken Ranch and like, Khan spawn positions, as well as pictures of the other map changes, just so we have them all in one place?

**Comment by GhostEcho** [comment]
Look Im just impressed when people dont just shitpost the description. Though I shitpost for my descriptions and had self merging powers at one point so gg

**Pull request merged**
