### PR TITLE
Fixes softcrit whispering

### PR DESCRIPTION
**Pull request by UndeadNappist**
@JTGSZ you no longer die while whispering in soft crit, only in hard crit.

The whole thing could probably be refactored to be under MESSAGE_MODE and the like, but I ain't doing it.

### CODE REVIEW

**Comment by JTGSZ** [comment]
I tested this, I was dying in any crit. By Softcrit you do mean when you are able to crawl around on the ground. Yeah?

**Comment by UndeadNappist** [comment]
Should be, yeah.

**Comment by GhostEcho** [comment]
So now softcrit lets you talk over the radio and doesn't register as "Barely conscious"

**Comment by UndeadNappist** [comment]
Fuck.

**Pull request merged**
