### PR TITLE
Mole rat & cazador sounds

### PR DESCRIPTION
**Pull request by ChronicPwnage**
## Description

Adds sounds to molerat and cazador attacks, they're royalty free.
## Motivation and Context

Issue #683

### CODE REVIEW

**Comment by JTGSZ** [comment]
You have your mood stuff mixed in with the sound addition in this pr, this is the latest of it yeah?

**Comment by ChronicPwnage** [comment]
> 
> 
> You have your mood stuff mixed in with the sound addition in this pr, this is the latest of it yeah?

Yeah I fucked that up, I think I mixed some stuff up with github (still new to it sorry)

Should I try to split it up or what?

**Comment by JTGSZ** [comment]
Up to you man, as long as its good to go its fine either way. I was just checking to make sure that new mood stuff doesn't get written over by old if this gets merged after it. Yeah?

**Comment by ChronicPwnage** [comment]
> 
> 
> Up to you man, as long as its good to go its fine either way. I was just checking to make sure that new mood stuff doesn't get written over by old if this gets merged after it. Yeah?

I haven't made any changes to the mood code just yet (though I have received some good suggestions) and I think it's good to go as a first implementation as is, though I will work on it further.

**Pull request merged**
