### PR TITLE
Update interaction_definitions.dm

### PR DESCRIPTION
**Pull request by UndeadNappist**
I am disgusted by myself.

## Changelog (neccesary)
:cl:
fix: Re-adds asslapping and handholding.
/:cl:

### CODE REVIEW

**Comment by rhicora** [comment]
I won't +1 but if someone else wants to that's on them. I think ass-slap is the most spammable and meme-encouraging interaction by far.

**Comment by UndeadNappist** [comment]
Could just put a cooldown on it. They all need a cooldown, honestly.

**Comment by Light-Weave** [comment]
I like handholding, but ass-slapping is low-effort LRP memery only used as an insta-escalate button.

**Comment by UndeadNappist** [comment]
Cooldown done.

**Comment by improvedname** [comment]
You want to ass slap? You have *me you don't need a fucking snowflake verb for every little thing

**Comment by RenGusta** [comment]
Ass Slap shall remain eternal

**Comment by UndeadNappist** [comment]
ERP was re-added.

**Pull request closed without merging**
