### PR TITLE
Removes Autosurgeon and Medbeam from RND

### PR DESCRIPTION
**Pull request by ScratKnapp**
## Description
Removes the Autosurgeon and Medbeam from RnD - doesn't touch the items themselves or any possible map spawns, just means you cannot research and print them.

While the items were removed from the tech web, the designs themselves has simply been commented out in case they're needed in the future.

## Motivation and Context
Requested by Ren, and I agree as well. 

The Autosurgeon allows someone (Vault and BoS, at present) to load themselves up with a bunch of fancy implants without any surgery, as if surgery wasn't critically under-used already. You can still aug yourself up, you just need a competent doctor to help you.

The Medbeam gun was infinite free heals, and using our simpler medical system it means that you can heal someone up from basically anything but being _dead_ with no limit of any kind. Make medicine instead, ya bums.

## How Has This Been Tested?
Tested on local server

## Changelog (neccesary)
:cl:
tweak: Removed Medbeam and Autosurgeon from RnD
/:cl:

### CODE REVIEW

**Comment by RenGusta** [comment]
If it passes checks, I'll be merging this in 24 hours, as per standards regarding all non-bugfix PRs.

**Comment by ScratKnapp** [comment]
God damn it, Travis. Let's try this again

**Comment by ScratKnapp** [comment]
image
Not sure what to do at this point, it's literally just a few line edits

**Comment by improvedname** [comment]
Keep the design, just remove it from the node

**Comment by ScratKnapp** [comment]
Un-commented-out the designs, so now they're just gone from the node

**Comment by MrBobCool** [comment]
Ew. Leave them in.

**Comment by Light-Weave** [comment]
Autosurgeon is terrible and should be removed, sure- but the medbeam is super radical. Why not make it charge-based with an internal cell (similar to laser weapons)? For every second it's beaming someone, reduce charge.

**Comment by RenGusta** [comment]
There is a plan for the replacement of medbeams with something less overtly technomagic/stupid. 

Going to give this a whirl, ignoring Travis because he's gay.

**Pull request merged**
