### PR TITLE
Changes min vote requirement 60, changes waittime between votes to 30, make shuttle autocall on succesful vote with admins on #2 (DNM)

### PR DESCRIPTION
**Pull request by GhostEcho**
#704 also valid concerns but better solutions to anti vote spam and closed too early

### CODE REVIEW

**Comment by improvedname** [comment]
Don't revive my prs

**Comment by improvedname** [comment]
copycat

**Comment by GhostEcho** [comment]
I wouldn't have to reopen valid PRs if you didn't close them in a fit, if you won't take criticism as criticism and essentially give a "Fuck off Im leaving" statement, then stop using your github powers

**Comment by GhostEcho** [comment]
Otherwise I will re-open those valid PRs

**Comment by improvedname** [comment]
>implying closed means cant be opened ever again>or uncommitable

**Comment by improvedname** [comment]
we been over this in DM's ghost.

**Comment by GhostEcho** [comment]
Yeah and I determined you were being a child. Now stop messing with github PRs if you're not going to participate in a non autistic way, if you're not going to stop working, then don't close your own PRs, if you're going to refuse to work on them, then close em

**Comment by improvedname** [comment]
How about you stay off my prs. i get to decide whether i close them or not. so hands off

**Comment by GhostEcho** [comment]
And I can decide if something is valid to make a PR out of because the concerns in said PR are valid

**Comment by improvedname** [comment]
no.

**Comment by improvedname** [comment]
so stay off my stuff

**Comment by GhostEcho** [comment]
If you're going to close your own valid PRs, then Im going to re-open them and do the work you don't want to do.

**Comment by improvedname** [comment]
Maybe you should stop being a faggot and stop taking my things over

**Comment by GhostEcho** [comment]
You had valid criticism, refused to address them instead just saying "no", Jt suggested a better idea than my own or yours, and you just closed both your active PRs and an issue out of spite, I'm not going to let valid things rust away because someone can't control their emotions

**Comment by Raze500** [comment]
Hyena please stop acting like a child man.

**Pull request closed without merging**
