### PR TITLE
Map Changes

### PR DESCRIPTION
**Pull request by JTGSZ**
Map changes.

## Description
Reduced Mobs
Removed Armor spawners from NCR lockers, gave them bedsheets.
Made bedsheets in places less boring.
Gave Farm Brahmin a chance to live.
Legion now has cotton seeds in lockers.

## Motivation and Context
Checked for something and just did a few extremely minor things while I was at it.

## How Has This Been Tested?
Hosted and tested.

### CODE REVIEW

**Comment by GhostEcho** [comment]
Someone else had brought this to my attention, but I'm curious just how bad was it? Like how many mobs did ya end up deleting?

**Comment by JTGSZ** [comment]
3

**Comment by kilozombie** [comment]
Why?

**Comment by JTGSZ** [comment]
ok, a chicken a carp and a cow on centcomm z level

**Comment by kilozombie** [comment]
That isn't even all you did, you can look at the diffs and see plenty more random miscellaneous changes

**Comment by JTGSZ** [comment]
I guess I moved somethings out of line of sight and away from the brahmin in the farms and changed some bedsheets.

**Pull request merged**
