### PR TITLE
Gives faction command, command headset, and gives legion command megaphones

### PR DESCRIPTION
**Pull request by improvedname**
Gives imporant faction command, a headset with high volume to make their text bold and make them more noticing then unders.

Gives legion megaphones because. HIGH VOICE MEANS VERY IMPORANT ORDERS 👏  👏  👏 

## Motivation and Context
somoene suggested on discord

## How Has This Been Tested?
works 👏

### CODE REVIEW

**Comment by improvedname** [comment]
Firstly.
No this doesn't allow to talk to eachother. it doesn't have a command encryption key.
Yes its true the /headset/heads being the path gets dragged over.
But due how new encryption keys are defined for the subpaths, they won't have the command channel

Secondly. this is mainly for like. Ok this is a imporant person speaking. for late joining recruits and such. you see somoene with high volume? you know hes command. and very imporant.

**Comment by RenGusta** [comment]
Or they use RP and words to convey importance. Not, "SHUT UP IDIOTS IM IN COMMAND"

**Comment by improvedname** [comment]
But its more statyfifying in.. =**Shut up IM in COMMAND**

**Comment by UndeadNappist** [comment]
Ah. Command = TRUE is for making extra-large letters over the airways.

**Comment by improvedname** [comment]
Eh theres a easy solution for raiders just remove the headset i mean, i dont care either just did what somoene suggested on discord

**Comment by Kimochiiiiiiiiiiiiii** [comment]
The Legion does not need megaphones, they follow the guy with the fanciest armor as warrior slaves, if they behave in any other fashion they are expected to, a high rank can call on beating them up, Decimatio is a thing.

**Pull request closed without merging**
