### PR TITLE
[WIP]Reworks protolathe material costs

### PR DESCRIPTION
**Pull request by improvedname**
Reworks material cost to be it in more touch with the autolathe costs.
Removes manipups ((for expirimenting, and if they manage add it later as design disks for the loot table)
Removes the omnilathe board design, NO this is not the bos protolathe, neither its the vaults. the omnilathe is a thing that allows you to make all designs. which the vault currently uses to bypass their departmental lathe lock.
Adds Rglass smelting recipe.

### CODE REVIEW

**Comment by GhostEcho** [comment]
Im going to ask that you speak with Tea and Ren and send me validation before I approve this from a review aspect

**Comment by AdamElTablawy** [comment]
1. departmental lathes don't sync with research at the moment and so researched technology won't actually show up for print

2. by virtue of human laziness this will just decrease the amount of cool shit the vault actually builds and won't affect gun production at all

3. it won't affect gun production because scientists will still get any lathe they want and nobody will protest the scientists having guns

4. the overseer is a role almost exclusively played by people who have played scientist long enough to unlock it and, accordingly, are just glorified scientists who will gladly authorize/move the sec lathe themselves

basically this PR prevents the vault from making things like DNA seed manipulators and other QoL machines because they have to go through a modicum of effort to build it 

and, in turn, all the vault will produce with R&D is guns-the exact opposite of what you are hoping to accomplish

additionally, removing manipulators is sort of shitty, as while they do impact material costs on some machines, material costs have become less of a problem ever since the hairbrained plasma cutter nerf and diamond rarity remains a concern (you're lucky to find more than 2, and manipulators can increase that to a far more reasonable 8 sheets)

and they also unlock decent functions on most machines, like the DNA manipulator, speed boosts on the autolathe so you don't sit around all day trying to print shells, and the sleeper, to which it gains chemicals actually capable of treating more complex problems like poisoning

bad pr

**Comment by improvedname** [comment]
> 3\. tists will still get any lathe they wan

big mood

**Comment by improvedname** [comment]
> 1. departmental lathes don't sync with research at the moment and so researched technology won't actually show up for print
> 2. by virtue of human laziness this will just decrease the amount of cool shit the vault actually builds and won't affect gun production at all
> 3. it won't affect gun production because scientists will still get any lathe they want and nobody will protest the scientists having guns
> 4. the overseer is a role almost exclusively played by people who have played scientist long enough to unlock it and, accordingly, are just glorified scientists who will gladly authorize/move the sec lathe themselves
> 
> basically this PR prevents the vault from making things like DNA seed manipulators and other QoL machines because they have to go through a modicum of effort to build it
> 
> and, in turn, all the vault will produce with R&D is guns-the exact opposite of what you are hoping to accomplish
> 
> additionally, removing manipulators is sort of shitty, as while they do impact material costs on some machines, material costs have become less of a problem ever since the hairbrained plasma cutter nerf and diamond rarity remains a concern (you're lucky to find more than 2, and manipulators can increase that to a far more reasonable 8 sheets)
> 
> and they also unlock decent functions on most machines, like the DNA manipulator, speed boosts on the autolathe so you don't sit around all day trying to print shells, and the sleeper, to which it gains chemicals actually capable of treating more complex problems like poisoning
> 
> bad pr

big mood

**Comment by AdamElTablawy** [comment]
accurate mood too, but it's nice to see you're too stupid to acknowledge a single flaw with your 'design'

**Comment by improvedname** [comment]
im just giving attenion so you feel like your being right 👏

**Comment by codexcode** [comment]
Mediocre coder, shitty result

**Comment by improvedname** [comment]
@AdamElTablawy 
Your balancing sights is nerfing around the deathmatch aspect, 

If these vault overseer mains want to give their fuck scientist boys a sec lathe, its clearly not even a RP standpoint, but mainly powergaming 👏 

and if you want your manips you gotta find yer design disks(soon TM), fallout is all about limited resources. thus you should be smart with your resources and not go braindeadmode and pump out 300 magazines/guns/medibeams/implants/toolsets/tools.

ammo costs are in touch with the autolathe one, i mean 667 metal for 30 bullets for your OP rifle you got for 1666 metal then good fucking shit 👏 thats too cheap throw more resource management into it

this isnt a deathmatch server, so balance like increased healing powder doesnt auctally matter 👏

**Comment by AdamElTablawy** [comment]
sure, but on the other hand, two sheets of diamond for one bluespace power cell.

also there's nothing that will stop the overseer from doing that and your manipulator research disks aren't in.

your changes are bad. i don't need to convince you of that, though.

**Comment by improvedname** [comment]
bluespace power cell cant even made so why do you care

**Comment by AdamElTablawy** [comment]
oh it can still be made

just takes a little finagling.

10 sheets of uranium for one NV goggle.

seems about right.

also, again, decrease in sleeper efficiency, etc.

**Comment by improvedname** [comment]
go fuck off with your expirimentor memes dont act so high 👏

**Comment by RedTekRedd** [comment]
Good argument from @AdamElTablaway
So what if it isn’t a death match server? Balance is fundamental to a good gameplay experience.

**Comment by JohnOxford** [comment]
i think removing or changing anything to facilitate rp is objectively bad and goes against the fundamental aspect of roleplaying on the basis that players create and follow through with it on their own accord.

this isn't bay, but this also isn't traitor deathmatch.

**Comment by AdamElTablawy** [comment]
not like this facilitates RP in any way lmao

**Comment by improvedname** [comment]
But 800 metal  30 55.6 bullets magazine vs 40 bullet box anyone in the wasteland with a autolathe can make being 15000 metal is still a big difference. You want your convience you pay for it im readding the manips designs.
But + the most things halved it will atleast cost a full metal sheet and such.

**Comment by RedTekRedd** [comment]
it failed

**Comment by improvedname** [comment]
@adameitablawy

You are correct im giving manips back giving vault a server that way the magazines and other stuff will atleast cost a full sheet

**Pull request closed without merging**
