### PR TITLE
Lobby images update

### PR DESCRIPTION
**Pull request by Arkatos1**
## Description

This PR updates lobby images:

1) Initial image is now randomly chosen.

2) Images will now always transition into another image, no chance of them transition into the same image in row.

3) Removes 2 duplicit images.

4) Adds 1 new image to the image rotation commissioned by server staff. Image made by jupiter, tumblr@jupitersdyke.

## Motivation and Context

Better splashscreen behavior.

## How Has This Been Tested?

Locally without any issue.

## Screenshots (if appropriate):
New splashcreen image, made by jupiter:

commissionweezer3

## Changelog (neccesary)
:cl: Arkatos
add: Lobby images update - Removed 2 duplicit images, added 1 new one made by jupiter, the initial image is now randomly chosen, and the images wont transition into the same image now.
/:cl:

### CODE REVIEW

**Comment by Hekzder** [comment]
The new image is going to look super, super, super out of place with all of the others. Given that all of the other title images have the same filter applied to them.

**Comment by ryai11** [comment]
Want me to put on a brown filter over this to help match?

**Comment by Arkatos1** [comment]
If you make a version of that artwork that is filtered, you can PM me it on Discord and I will replace it.

**Comment by ryai11** [comment]
Edited the image and it's in interstice.

**Pull request merged**
