### PR TITLE
Fixes NCR Recruits spawning with wrong ammo

### LINKED ISSUE #687: Spawn w/ wrong ammo (NCR Trooper)
[Priority]: # (Is it game breaking? Mostly)

Round: 1170

[Reproduction]: Spawn as Trooper. Have in inventory Remmington, description says Chambered in .308. Unload found from rifle. It's a .308 round. Open backpack. Observe 3 7.62 stripper clips. Try to apply 7.62 stripper clip onto gun. Doesn't load. Remove 1 round from 7.62 stripper clip. It's a 7.62 round. Try to apply it to gun. Doesn't load.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

[Notes]: This effectively means Troopers get 5 bullets and their 9mm, plus 3 clips of garbage.

### PR DESCRIPTION
**Pull request by JohnOxford**
fixes #687

### CODE REVIEW

**Comment by GhostEcho** [comment]
Make sure to look at rangers and legionnaires too

**Comment by extramrdo** [comment]
Lieutenant has a762 doublestacked but a hunting shotgun (The Colt Rangefinder), 
vetranger has a762 doublestacked and remington scoped, 
ranger has huntng shotgun but a762 doublestacked (The Colt Rangefinder), 
Recon Ranger has a762, remington scoped.

CaesarsLegion/Legionnaire/f13scout has a762, remington scoped

At this point it almost makes more sense to revert the change that made 308 a separate ammunition, and either change the remington's description from "chambered in .308" to "chambered in 7.62", or refactor a762 entirely. Is there a good reason for having a762 and a308 simultaneously as completely unrelated ammunitions?

**Comment by RenGusta** [comment]
I don't know what idiot even changed their weapon types as is. They were fine.

**Comment by GhostEcho** [comment]
close it Ill do a different fix

**Pull request closed without merging**
