### PR TITLE
Admin(AgentAgent) says, "Adam, please make a PR buffing deathclaws"

### PR DESCRIPTION
**Pull request by AdamElTablawy**
Admin(AgentAgent) says, "Adam, please make a PR buffing deathclaws"

die

### CODE REVIEW

**Comment by SpaceVampire** [comment]
I approve of this change, the server is called bad deathclaw but our deathclaws are a joke. This PR is instrumental to our servers success and if it inst speed merged right away the system has failed us.

**Comment by SpaceVampire** [comment]
Actually they still do almost no damage, maybe buff that as well.

**Comment by AdamElTablawy** [comment]
done

**Comment by SpaceVampire** [comment]
OwO Ok, I was actually fine with the health change but 500 is a little much. Maybe just double the old amount would be good?

**Comment by AdamElTablawy** [comment]
done

**Comment by SpaceVampire** [comment]
Did you buff mommy deathclaws as well?

**Comment by pireamaineach** [comment]
Holy fuck why please no

**Comment by MrBobCool** [comment]
maxHealth = 500
	health = 500
	maxHealth = 5000
	health = 5000

Haha. Stop no.

**Comment by AdamElTablawy** [comment]
i was asked to buff deathclaws

nobody told me how much to buff them, so i decided to make it a nice reasonable round number divisible by 50

i am not accepting constructive criticism at this time

**Comment by SeniorScore** [comment]
I hate every last one of you.

**Comment by GhostEcho** [comment]
Just no

**Pull request closed without merging**
