### PR TITLE
Admin Ranks Changes

### PR DESCRIPTION
**Pull request by JohnOxford**
**THIS IS THE MOST IMPORTANT POINT I HAVE TO MAKE**
Initiate isn't trial mod its admin candidate
Aspirant isn't mod its Trial Admin
Knight isn't trial admin its full admin
Paladin isn't admin its game master
head paladin is "head admin" or super senior admin or whatever the fuck you want to put them as

I made a two page PDF with eight more paragraphs that was organized OH so neatly that i spent SO much time making presentable and readable that can be found here:
https://docs.google.com/document/d/1s6W2X7DAJoFpwmXjnR-SQfDiiJp--OOfPrVupg_p32s/edit?usp=sharing

In that document i explained the above statements and the role of each position and how it interacts with every other position. Consulting this document before making any PR's that changed the admin ranks would have prevented this problem.

**THIS IS THE END OF THE MOST IMPORTANT POINT I HAVE TO MAKE**

This addresses the following problems that were brought up with my original PR, discussed for six days, and then fixed, and then subsequently created again in the PR that changed admin ranks afterwards

From what i understand +@ gives the rank roles from the one above it, but if the one above it also has +@ that would additionally mean that it would get the roles from the one above that one.

- There is a acute distinction between people who need and understand debug verbs and people who don't need and don't understand debug verbs. Paladins have no use for them and the use they could possibly get out of them is already accomplished with +SERVER. If you can have the majority of paladins say in coding public what dynex is and i'll change this immediately.

- Initiates can ban people, in cases of grief, they also need to be able to revive people. A simple situation that was brought up in the previous PR. You took the only joy they had away by removing +SOUND, so at minimum understand that they can at least seek joy by allowing other to finish their already hampered round.

- The majority of the admin team should be able to create polls, not only scribes and head paladins+. Problems requiring player base input affect all levels of leadership, not just senior leadership, allowing only a select group of the most senior members of the admin team to create player polls is essentially pocket democracy and you should feel ashamed for it.

- We had a LONG and LENGTHY discussion about specifically what verbs both developers and admins should get, i'll concede that +STEALTH isn't necessary for anyone but paladins, and that it isn't really necessary for anyone at all. All the permissions that both the Head Scribe and Scribe had originally, with the exception of +STEALTH, were discussed in painful detail among key members of the administration team and quite literally the entirety of the development team individually, where we argued from each side why we would need those verbs, and the verbs listed were the final product. The majority of the argument essentially boils down to "testing" and "fixing problems that arise during game play" and "making use of existing verbs that admins wouldn't be able to effectively use", like +DEBUG for example.

- Knights need possess and sound for obvious reasons, fundamentally normal admins make up the majority of the administration team and are primarily tasked with running events. Possess also gives the ability to immediately ( 30 seconds quicker ) stop grief / actions that would otherwise damage the server or its population by possessing the person and kicking their ckey out of their character. Additionally sound files are played for event moods, setting a round mood in general, lore related speeches/dialogues, or actions that are happening in the metagame that need to be referenced into the actual game.

- It was painful to manage the roles when i made my original PR and it was painful to manage them when i had to essentially remake it. +@ is really nice and really convenient and all but being able to explicitly see which permissions each role has because i neatly organized them in columns under any format is significantly better, i realize no one else in the universe has that level of tenacity but fundamentally i didn't expect anyone to touch it anyways after so much deliberation over such a long period of time.

-more points to be made, reviewing the previous PR-

### CODE REVIEW

**Comment by Autismobirb** [comment]
I just woke up to this and I can tell this is a headache waiting to happen.

So I'm gonna blitz out some quick statements. 
First of all, read the code on what half of the perms actually do POSSESS is nothing to do with taking control of players, that is done through +admin and Varedit or the admin dragging his ghost to the player in question, this boots them out. POSSESS is coded to functionally let a admin take control of a static object and meme around with it

Poll was moved to higher ups of each department to force communication between them if they want anything polled, simple as.

Your "LONG and LENGTHY discussion" didn't include me or Ren to my understanding. hence why we went through and fixed it with what we felt they appropriately need

Admins make fair use of the Debug tools, my higher echelon of cunts mace common use of most of the perms that are supplied with it, and any admin who cant make proc call be a great admin tool has never admined with efficiency before.

Clear and distinctive perms in the document is no excuse for bloat. if they cant read through the +@ then they shouldn't be messing with it, if you don't understand what is essentially a parent call you shouldn't be touching the thing.

My apologies for sounding like I'm riddled with spite here, But I find it very amusing that a coder has attempted to tell me what the official rank structure of my own server is.

Initiates ain't banning shit, there trialmins/mentors.

"Knights need possess and sound for obvious reasons" Knights cant be trusted to tie there own shoes half the time and i'd rather keep this for admins and above only

lastly +Rejuv is a Baycode flag you absolute fucking nonce, Unless you can cite me its usage anywhere as I cant find it anywhere in admin flags and there is nothing pointing to it otherwise, Rejuvenate is under the R_ADMIN section.

**Comment by RenGusta** [comment]
I want to add a DNM on this for the moment, but can't do tags on mobile. Someone do that until it's brought to the table.

**Comment by Autismobirb** [comment]
My perms are fucked at this precise moment and time, I asked politely that John closed this as it was denied from the higher ups. couple hours later aint been done so I'm gonna dump this
image
and call it a wrap

@improvedname Be a babe will ya'

**Pull request closed without merging**
