### PR TITLE
Adds molerats (Not sure if I did it right)

### PR DESCRIPTION
**Pull request by GoodG1448**
¡¡ MIGHT NEED TESTING !!
 
Do not merge until tested. I guess this will do for now, change the damage values as you see fit.

### CODE REVIEW

**Comment by kilozombie** [comment]
This doesn't include any icons so I'm not sure if there are already mole rat icons in the code or if you forgot to include them

**Comment by GoodG1448** [comment]
Yeah, the icons I used are in already in the repo.
https://github.com/BadDeathclaw/TG-Claw/blob/master/icons/mob/wastemobs.dmi

**Comment by GoodG1448** [comment]
I have no fucking clue what is going on.

**Comment by UndeadNappist** [comment]
Click on details for travis build.
image

**Comment by GoodG1448** [comment]
> 
> 
> Click on details for travis build.
> image

I take the errors are in line 199 and 200 on wasteanimals, right?. If not, not sure what is trying to tell me.

**Comment by improvedname** [comment]
Sometimes travis just has a stroke, @GoodG1448

**Pull request merged**
