### PR TITLE
removes psycho not giving you psychotic brawling as a trait instead of psycho trait which is bad

### PR DESCRIPTION
**Pull request by AdamElTablawy**
trans rights

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
I don't like this under the table nerf or see why it had to happen besides the abstract possibility you died to it & some guy huffing on turbo at the same time with a fire/bone axe or bumpersword as is often the case of stacking drugs on this server.

_**[Instant aggressive grabs are pretty strong](https://github.com/BadDeathclaw/TG-Claw/blob/d6ffeb207849abcc3d993d4326ee0cef6c9c1a73/code/datums/martial/psychotic_brawl.dm#L35)**_ , **_[and self inflicted stun times that can be dispelled with med-x](https://github.com/BadDeathclaw/TG-Claw/blob/d6ffeb207849abcc3d993d4326ee0cef6c9c1a73/code/datums/martial/psychotic_brawl.dm#L49)_** for additional balancing discussion.

This removes the ability of extra pvp/pve melee damage from players & iron fist would also do a flat 5 more damage  **_[in the headbutts ( to themselves depending on damage sources)](https://github.com/BadDeathclaw/TG-Claw/blob/d6ffeb207849abcc3d993d4326ee0cef6c9c1a73/code/datums/martial/psychotic_brawl.dm#L45)_** and raise the damage of **_[the metoric sucker punch to 35 flat brute damage.](https://github.com/BadDeathclaw/TG-Claw/blob/d6ffeb207849abcc3d993d4326ee0cef6c9c1a73/code/datums/martial/psychotic_brawl.dm#L56)_**

Its either really strong with powergame chemical combinations, or just really bad when faced against actual weapons like guns aimed at obvious areas like the head where self damaging and possibly sending themselves into crit is unavoidable on rng.

**Comment by AdamElTablawy** [comment]
what about this is a fucking nerf

**Comment by FantasticFwoosh** [comment]
Using less than optimal weapons like a explorer/combat knife (or overblowing high damage weapons like previously described bumper sword) with the removed psycho benefit may mean melee dedicated players will struggle head on against mobs who are hard hitting, high health or bullet resistant, like deathclaws for instance without the trait stacking added damage.

Its a pretty fringe balancing point but it is a thing that happens when you run out of ammunition but dont want to leave the ruin loot alone with weakened guardians while you run back to resupply your ammo to find someone's polished them off and took what you were after. Pop your powder and attack buffs and you can continue the fight.

**Comment by AdamElTablawy** [comment]
if you're using psycho and a combat knife to kill a sentrybot you're dead anyway

**Pull request merged**
