### PR TITLE
Map improvements, advanced signaler, brahmin calf, cornu.ogg

### PR DESCRIPTION
**Pull request by rhicora**
- Improves the Legion section of the map.
- Fixes the Den buildings up against walls.
- Separates the vault from humanity.
- Fixes collar codes.
- Adds the advanced signaler, which can store 5 units.
- Adds brahmin calf.
- Adds cornu.ogg.
- Handcraftable tortillas.

### CODE REVIEW

**Comment by rhicora** [comment]
There is a better way to handle signaler code but this works and I am too tired to refactor it.

If cows become a problem we'll add a global limiter.

Global slime limit is not within the scope of this PR.

**Comment by rhicora** [comment]
Oh, cows don't autobreed. You have to actively feed them a wheat first.

**Comment by rhicora** [comment]
If you have any specific line-level improvements you want to see with signal code let me know and I'm happy to change them. Otherwise approval would be nice.

**Comment by UndeadNappist** [comment]
If you'd leave me a line on how to go about refactoring this, I'd love to hear it, because I need to apply it to a bunch of different things.

**Pull request merged**
