### PR TITLE
Enclave Mountain Bunker V2.0

### PR DESCRIPTION
**Pull request by Light-Weave**
## Description
Remaps the enclave mountain bunker- it's now a scientific/medical research outpost. There's less shooty guns and more cool medsci tech- notably a medibeam gun, inducer, and working viro and chem lab. The horrifyingly overpowered gauss rifle spawn, as well as the weapon and armor spawns, have mostly been moved to the deathclaw nest to the south, which has been updated with some *really obvious danger signs* such as land mines and bodies.

## Motivation and Context
It's cooler now, and you can't get a t4 gun at roundstart by cheesing a few gutsies. We need more dungeons with noncombat loot. If you're feeling really adventurous, you could take it on and make some doctors, engineers and scientists very happy indeed.

## How Has This Been Tested?
Ayup.

## Screenshots (if appropriate):
https://i.imgur.com/KIUrVlp.png

## Changelog (neccesary)
:cl:
tweak: Remaps the Enclave mountain bunker and deathclaw tunnel.
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
>medical bunkee
Tfw. Virus research.
Tfw. Chemistry.
Tfw showers.
Tfw. Still no biohood hazard suits to justify the safety of the bunker

**Comment by Light-Weave** [comment]
smh there's a biohazard locker with suits in it

**Comment by Light-Weave** [comment]
also I used the mapmerger so it only breaks others if they didn't

**Comment by GhostEcho** [comment]
This shouldn't have the ability to do viro because that has led to massive issues in the past, and it has been idiotically buffed to stupid extents for ??? reason

**Comment by Light-Weave** [comment]
Viro machines replaced with *experimental cloner*, which is perhaps even more enclavey.

**Comment by Light-Weave** [comment]
if we buff deathclaws the risk will justify the medbeam gun *taps nose*

**Comment by UndeadNappist** [comment]
Medbeam isn't strong compared to just shooting people with healing shotgun darts. Add them to the R&D machine, who cares.

**Comment by improvedname** [comment]
@UndeadNappist you are correct. but don't forget due how explosions work by atmos. the negative of the medbeam cross effect can be combined to instakill your targets rn.

**Pull request merged**
