### PR TITLE
Borg stuff

### PR DESCRIPTION
**Pull request by RedTekRedd**
adds pleasure borgs to module list
also, sets default borg sprite to handy
also also sets medical borg sprite to medical handy.

### CODE REVIEW

**Comment by improvedname** [comment]
Ree im doing the standard module borg sprites

**Comment by RedTekRedd** [comment]
it was changing a few lines, and I was already editing the file. The rest of the sprites are yours to do.

**Comment by RedTekRedd** [comment]
fixed pr because hyena is screeching autistically at me

**Comment by Raze500** [comment]
P-Pleasure module? oh no **what the vault has become**

**Comment by improvedname** [comment]
That mr hand fisto could be a genious tentacle joke

**Pull request merged**
