### PR TITLE
updates ncr base, gives vault caves a mineable entrance

### PR DESCRIPTION
**Pull request by companoo**
## Description
gives ncr a reloading bench, chem dispenser, and changes there southern fences (gate still has chainlink) for den walls. gives the vault caves a mineable entrance, so its a bit out of the way, but vault can sometimes do something in a round if there is a disaster, and they already use the chute anyway. some guy wanted slave collars

i dont know how to use mapmerge tools please dont sue me

## Motivation and Context
ncr grabs reloading bench + chem dispenser anyway, requires there walls to have more then wirecutters to bypass, lets vault go to the outside if its destination fucked, but its not as easy for joe schmo to walk in since its covered by cave. legion have to find a seed extractor anyway, blood bags and radaway give use to there iv drips.

## How Has This Been Tested?
everything works

## Screenshots (if appropriate):
https://gyazo.com/ed47a11923eef63a7df04698b6b79d60 new ncr walls
https://gyazo.com/6fca853a0f735e564d3eb75bb1157522 (vault is mineable)
https://gyazo.com/989896b0bf28bb373b33692d407e0296 **(new vault is mineable)**

## Changelog (neccesary)
:cl:
add: universal reloader to ncr base, chem dispenser to ncr base
add: new ncr composite walls
add: slave collars to the raider mall
add: seed extractor to legion
add: blood bags and radaway to legion hospital
add: ncr get a chem heater and a chem master
tweak: increases the area for mining of the vault
/:cl:

### CODE REVIEW

**Comment by companoo** [comment]
unsure why travis is a pain in the ass

**Comment by improvedname** [comment]
- on the vault caves thing, random seeds paths out a minable area every round, shown by the blue/red boxes what your doing is making the path always the same like it was before which is gauranteed and stupid

**Comment by SpaceVampire** [comment]
If you are giving the NCR stuff so they don't have to go and get it, why not just give the legion farming equipment like the Seed Extractor so they don't have to go and get it? Maybe some blood bags as well because they have IV-drips but they are actually never used.

**Comment by GhostEcho** [comment]
I second Vampire

**Comment by SpaceVampire** [comment]
The Legion also needs a reliable way of purging toxin damage without using chems. Maybe start em off with a couple of charcoal bottles or make a way to get it by burning wood? Because I see them get attacked by mobs outside that base that deal it and have no way of solving the issue.

**Comment by companoo** [comment]
done all of what you guys have said

**Comment by Light-Weave** [comment]
NCR also needs a ChemMaster and chem heater if you're giving them a chem dispenser.

**Comment by SpaceVampire** [comment]
The NCR really needs a lot of the ammo and guns already in the armory removed. Given that they have a universal reloader now, its just not necessary. They can fill it up during the round instead.

**Comment by Light-Weave** [comment]
I vote toss the speedloaders (used only by Rangers, who have their own ammo stock at the outpost) and some-but-not-all of the shotgun shells (used by heavies/sergeants), keep the 5.56/9mm mags. The reloading bench is awful for metal efficiency, so it's not intended to be a primary source of ammo- they still need to keep the ammo for their main weapons.

**Comment by SpaceVampire** [comment]
Troopers already spawn with a full service rifle and three extra clips. Then you have four more full rifles in the armory, and eight clips for them with 20 shots each. Its just not needed. I'm not sure if the ranger outpost should have all that ammo either.

**Comment by SpaceVampire** [comment]
Also, is the Legion even allowed to use radaway? It kinda sounds like the type of thing they wouldnt do.

**Comment by Light-Weave** [comment]
Speaking of Legion not being able to use lathes, maybe give them a reloading bench too if you're giving one to the NCR. Legion arguably needs it more.

**Comment by companoo** [comment]
ren keeps saying he doesen't like this PR but is too much of a fatass to comment

**Pull request closed without merging**
