### PR TITLE
Revert "re-ads erp"

### PR DESCRIPTION
**Pull request by rhicora**
If you want to make a major change like this, have a discussion in the appropriate 24 hour window and do not speedmerge after 5 hours.

### CODE REVIEW

**Comment by UndeadNappist** [comment]
image

**Comment by Light-Weave** [comment]
Speedmerge because the original PR was invalid.

**Comment by rhicora** [comment]
Staff who are willing to talk constructively about how to resolve the RP / ERP issues, contact Ryai and we'll put together a group chat. Hold off on merging til then.

**Comment by annoyedbunny** [comment]
hi there, im a player who was told to come here to whine about the idea of removing erp. let me just say that i think its a terrible idea to remove a very popular feature in hopes that it will improve a problem that it has nothing to do with, lrp players will not stop being lrp just because they cant spam slap ass, this will only result in a drop in players good and bad and do nothing to fix the issue of lrp at the core, which is the lrp players themselves. please dont remove this feature that makes this server unique

**Comment by JTGSZ** [comment]
I'm all for removing them. Time for them to go, perhaps BD will be better, perhaps worse with the new direction its taking. Who knows.

**Comment by ParadoxalObserver** [comment]
I can't count the number of times this has been suggested and pushed back. At this point, this feels more like a personal preference trying to be pushed in through the cracks than an actual suggestion that might improve anything.

Anyhow: 
Fallout has always been a mature Universe with everything from starved, broken people working the oldest profession to blowing half of a man's torso off for talking to you in a rude way. I don't see how this at all stays true to Fallout's themes, for one.

It limits roleplay. Really, it does. Whatever your opinion on ERP, it's still RP, it's stripping an option away, again due to personal preference. 

It limits options on a codebase actually stressed for them. You immediately remove concepts such as making a brothel, working as a prostitute, you remove another reason for raiders to raid and be sadistic pieces of shit.

Generally, I don't get how this improves things. This is about the same as: "Well, there a meta'ing players that rush good weapons and low-RP escalate to get a power kick. Let's remove violence so they can't do that!"

So against since: it limits options and doesn't actually demonstrate any benefits to its existence. "This may or may not be a good choice" isn't much of an argument in favour.

**Comment by Light-Weave** [comment]
It should be noted that this PR doesn't actually remove ERP. It just removes the ERP verbs you see when you right-click people and 'Interact With' them. You can still do brothels, prostitutes and weird creepy rape scenes (but if the other player is uncomfortable with it, don't). You just use /me instead of clicking the "Fuck Ass" button.

After a long and ultimately pointless chat among the staff team, the conclusion was that it's Ren's call because nobody can agree on whether or not ERP verbs are good or bad.

**Comment by ParadoxalObserver** [comment]
Mmm. It's not my call but thought I should voice my opinion. Personally, again, I think the verbs are good. They're a nice mechanic that incentives using them and in turn creating a player economy (granted, I do think something such as a longer lasting moodlet would be nice, but that's a different conversation). 

The verbs are nice because they don't stop you from using "me" to ERP (if that's what you want) and it allows this to actually be used in a mechanical fashion. The removal of verbs, in my opinion, leads more to a group of people isolating themselves more to be able to "me" a whole ERP scene out instead of actually interacting with the world and seeking things like prostitutes and contributing to round interactions.

I suppose to compare it to this: imagine removing weapon damage and instead have combat interactions resolved completely through "me". I personally just find it a tad silly and (again) don't see this fixing anything.

**Comment by skateboardjones** [comment]
Verbs bad. Destroy.

**Comment by UndeadNappist** [comment]
After some discussion this boiled down to two important questions:
"What does having these in the server add?"
and
"What does removing these from the servers cause?"

The argument boiled down to a few basic things:
One, that a button that you can spam does not cause people to be more inclined to roleplay or do anything except meme.
Two, that the button _does_ introduce a player to various ideas, including writing and gameplay.
Three, that it is a poisonous addition that lowers the player quality and gives outsiders and newcomers a bad perspective on the server.
Four, that removing it will kill the server as it did the previous one when ERP verbs were removed.

The majority consensus and talking (particularly with the load of players being stressful on admins, and the observations by various groups) have come to the conclusion removing them is likely a net positive.

I will say in a closing statement I find it extremely distressing that this is a huge point of contention either way instead of an 'okay, whatever,' because if it was 'just a joke' it would be felt that way and there would be minimal argument.
The other note to make is that making players feel forced into a situation that makes them acutely uncomfortable or unpleasant - whether it be playing or otherwise - is not a good nor healthy thing for people.

**Comment by ParadoxalObserver** [comment]
Hm. I disagree on there being a "consensus". People constantly repeating it - namely the same people over-and-over again - doesn't really make it a "consensus" if anything the few polls I remember being hosted on the matter actually pointed against its removal repeatedly. 

I doubt it'll cause the death of the server. It'll make some people quit, no doubt LRP players, but it won't by any means fix the LRP issue. 

On the issue with the verbs - I don't think "there are some fixable issues" should be engaged with "delete a great amount of code".

I also don't think it makes people uncomfortable is much of a point. People also get uncomfortable with being enslaved and nailed to a cross. Should we remove Legion? Some people get uncomfortable with losing. Should we remove weapon damage?

As said, I do think it adds mature themes and a bit more depth if handled well. Let's say that I as a merchant accept sexual favours. Are you saying I should be forced to "me" out an awkward scene for 30 minutes instead of using verbs? Yet, for some reason, the proposition of this as a narrative happening is, for whatever reason, considered utterly baffling and degenerate. Yet, if you had a scene with a book of the same, it would be believable and acceptable.

Point being: limiting player options without a very good reason should never occur. I doubt its removal will have much impact on the player base or quality of it aside from removing sexual themes which, in my opinion, lessens Fallout's harsh vibe as much as removing the ability to bury people alive, burn them alive, nail them to the cross, etc. And, of course, people that are only interested in ERP will continue to do so, just that now they'll be "me'ing" for an hour in some hidden corner of the map.

Honestly, with the removal of verbs, I think ERP should just be made a bannable offence, as it's just incentivizing ERP-focused players to waste most of the round not interacting with a majority of the cast.

**Comment by Light-Weave** [comment]
You don't have to /me out an awkward scene for 30 minutes- you can just do "/me has sex." and fade to black. If you want the actual sex, you have to RP the actual sex.

**Comment by rhicora** [comment]
There are other outs to a scene where a merchant accepts sexual favors. Pay the merchant real money, or don't buy the thing, whatever. We are talking about situations where someone is expected to `me` out a situation when captured. Agreed with @Light-Weave that these should be fadeable.

**Comment by ParadoxalObserver** [comment]
Fadeable? Uh. Okay. Sure, fadeable - that's now a thing. Next I shall "fade-to-black" this bar fight. While we're at it, lets solve LRP by telling people: "Just make a low effort 'me' instead of using a simple mechanic or don't RP things at all and just saying: 'then this happened'."

I know the topic of ERP verbs can be a bit uncomfortable, but lets at least make proper points. As in, compare what you're saying to any scene that you might consider is "conventional RP". Does any of this sound like:
-It makes sense;
-Helps with the LRP issue.

Think about it, if you used this excuse anywhere else you'd be pointed at and told you're contributing to the LRP issue, but in this case, it's used as an excuse. If you're telling people: "Well, just making low effort mes to replace the mechanic we had" how does that stop people literally just making one-line mes like: "Slaps X's ass".

As said before: don't half-ass things. Just totally remove ERP if you're removing the verbs instead of giving these weird workarounds that sound worse than broken (yet fixable) verbs.

**Comment by S1lv3rv1x3n** [comment]
* ERP never was the reason of LRP.
  - There are niche ERP servers with more hugbox communities, easier interactions and higher amount of ERP-oriented kinky players.
  - The amounts of combat-oriented LRP is way higher, and situations of lowly roleplayed combat actions have higher numbers. You will barely see people using verb-ERP in 10 minutes gap, but you will see somebody using a one-liner to kill.
  - Verb ERP and rape "enforces" player to submit to what  happened to him during the playtime and has a higher chance of impacting his further roleplay. ERP if not fully removed should have a consequence as any other action taken on the server.
  -  Verbspam can easily be removed by adding spam filters. A delay between actions or whatever. Verbspammers are both removed ICly (by players) or OOCly (by admins).

* ERP makes interactions between players quicker, not taking them out of the game.

* ERP adds up to current leftover of TG mood system, which was a good, but janky idea with a better form of it on LW.

**Comment by RebornEdd** [comment]
I did provide my take on discord a few times, but here it is.
Firstly, i don't think this is the issue to tackle if tackling lrp is the goal. There are far bigger issues and erp is not even something i encounter unless i tried to search for it IC and i have seen plenty of decent usages that are there to add flavor to a story.

Next point is that those usages tend to not be for "erotic" purposes per say, the verbs are there to make it so you did have an erp interaction, creates the function of being able to do it. It doesn't have to be erotic at all, but it creates the whole idea that you may be forcefully abused/put into a shitty situation, which adds both to a storyline your character may be upon and in general adds a darker/more adult theme to the game and roleplay. (obviously it can be used for erotic if used correctly as well)

I do think this is more so for removal of ERP in general from the server, /me erp is just not viable in fallout 13 type of server, the game is quick paced and there are always people making restart votes every 10-15 minutes (whatever the limit is) and /me roleplay does take considerable effort, big chunk of time and safety to pull off unless you are really into it and are pretty fast at typing or were off locked in the corner of the map. What if i want erp only to add flavor to story and not to actually have anything erotic sometimes, verbs make it easier to erp without the actual erotic side of it (fade to black would be ugh, we might as well fade to black most interactions besides erp verbs make the interactions quick and well realistic in that sense especially when it's forced erp which verbs would remove). The best erp in this server would seem to be both verbs + chat +/me, a mix of all.

And of course the negatives, as always people tend to abuse things and it may attract some people, i really do not think it makes up a big part of the playerbase who come here just for erp. People will fail rp as they always do verbs ingame or not. Also the playerbase is pretty new for most part, as i remember this server having low numbers before the sethtide and i've seen plenty regulars be for erp verbs.

Which brings me to trying to at least see a third option and make the verbs limited in how often you can just spam them, maybe playtime limit before you can use them, remove the very stupid stuff you can do with them and just discipline as you would with any fail rp? Maybe, of course this is just an idea as i do think people who enjoy the verbs should not be disregarded because as some have said they supposedly don't add anything good to the game, which i do think is false and just antagonizes the other side.

Also do note i do not even ERP unless i am forced into such situations, yet i am fully for allowing verbs to exist maybe with some limitations.

**Pull request merged**
