### PR TITLE
Makes the game less fun by buffing all mobs in minor but annoying ways that make it more likely for the unprepared to die to them. 

### PR DESCRIPTION
**Pull request by AdamElTablawy**
changes cleared with ren. 

eyebots now use proper beam weapon.

radscorpions do less damage and inject toxin as is proper.

all mobs beat you to death.

super mutants meaner.

sentrybots mildly meaner.

## Changelog (neccesary)
:cl:
balance: all mobs will now beat you to death
balance: the game is now less fun
/:cl:

### CODE REVIEW

**Comment by JohnOxford** [comment]
masochism: the PR

**Comment by companoo** [comment]
i like this

**Comment by CatSpaghoots** [comment]
i dont like this

**Comment by walrathdam** [comment]
I dont like this either. Your games more or less over if your in crit and surrounded. I dont mind damage buffs or the toxin changes tho. It lives up to the title of making the game less fun I supposed

**Comment by AdamElTablawy** [comment]
I genuinely give less than zero fucks if anyone has negative feedback on this on the grounds of 'I don't want to die if I go into crit around a simple mob' and all arguments to that effect will be entirely ignored.

The only thing i'd be open to is numbers tweaking, with reasoning, on some of the buffed mobs.

**Comment by SpaceVampire** [comment]
Buff ghouls as well, mostly the glowing ones. They should be scary. The radscorpion thing isnt needed, as its already been done I'm pretty sure, the eyebots agro range is stupidly long, deathclaws should be faster, supermutant are now disportionately stong relative to the areas they are balanced around, probably some other shit is dumb as well.

**Comment by AdamElTablawy** [comment]
I'm not buffing ghouls, deathclaws are as fast as is reasonable for something that can charge you and kills you in melee range faster than you can melee it, and super mutants are just fine considering they guard the best loot pinatas.

**Pull request merged**
