### PR TITLE
removes shitty spraytan

### PR DESCRIPTION
**Pull request by JohnOxford**
literally just breaks spraytans

as opposed to having to remove the bottles on the map that contain spraytan, we just made it literally not work

i expect people to make bug reports about how spraytan doesnt work

### CODE REVIEW

**Comment by rhicora** [comment]
This is not the correct way to solve the problem. Instead:

Cut a new branch, delete `/obj/item/reagent_containers/spray/spraytan` and all underlying code, then open the map. It will complain that it doesn't know what a spraytan is, and ask you what you want to replace instances of it with. Choose nothing.

**Comment by JohnOxford** [comment]
that causes a map edit, even something as simple as that wont get merged fast enough to justify doing it that way and it will fuck over everyone elses map edits.

**Comment by rhicora** [comment]
The correct fix requires a map edit. Ask around if anyone else is working on a map change then do it.

**Comment by JohnOxford** [comment]
you bring me great pain and suffering

**Pull request closed without merging**
