### PR TITLE
Mob Migration 2: Electric Fork Update Edition

### PR DESCRIPTION
**Pull request by GhostEcho**
Remember kids, update your fork before working on things

Some scorpions have appear to migrated towards areas, attracted to the scent of people frequenting these areas. Raiders have also appeared to take over the super mart from it's previous ghoulish inhabitants, bringing in some meds, drugs, and average weaponry. Someone has also installed some more robust security in the prison armory, or has it always been this way?

Also prepares apc areas to be more sensibly constrained to buildings, and for sand storms looming on the horizon

**Screenshots**
image

image

image

image

image

image

### CODE REVIEW

**Comment by improvedname** [comment]
Pictures with map edits please

**Comment by GhostEcho** [comment]
https://imgur.com/a/1sfUi7N there's also a bunch of area changes to make them be within their buildings but Im not taking a screenshot of all of that

**Comment by GhostEcho** [comment]
Also considering this is a balance change,  I would like some discussion over it

**Comment by GhostEcho** [comment]
So a few vaguely irrelevant, but still irrelevant thoughts to this, the raider mart should be harder to clear now as the raiders are both ranged, and have generally more health, for this I added a few t2 weapon spawns, (2 or 3 I forget exactly off the top of my head), some more meds and drugs as well to make it a bit more rewarding, furthermore currently the raiders don't actually drop any weapons of their own since the ones they would drop would be kinda oofy.

The two scorpions outside the checkpoint may wander off, so that may be up for change at somepoint if it isn't as effective of a defense as hoped

loot in the prison hasn't been adjusted since it's already pgood and the new mobs will provide more of a challenge, and allow for player ghouls to meme around with ferals again without free loot memes

**Comment by GoodG1448** [comment]
As far as I remember the ranged raider mobs used to eject casings each timed they fired their weapons. There was this big issue were a raider would target a ghoul that was behind a fence and would shoot at it for an eternity, which would later cause massive lag spikes when having line of vision with the casing piles underneath the raider.

This was legacy, to point out a detail: Wirefences weren't destroyable in Legacy so shouldn't be an issue nowadays. I don't remember if Gomble did something about it.

**Comment by JTGSZ** [comment]
Worst comes to worse, casing ejection can be removed from the raiders.

**Comment by GhostEcho** [comment]
Yeah it *shouldnt* be an issue but thats something I haven't tested but when Im back fron $2 margaritas I will

**Comment by JTGSZ** [comment]
also woops i accidentally closed this, sorry.

**Comment by UndeadNappist** [comment]
Keep in mine(d) that radscorpions are tougher and have a higher damage output than adult cazadores at this time. Other than that, looks good to me, but I'll leave it open for a bit longer.

**Comment by GhostEcho** [comment]
That's why they're around the t3 spawns in areas with two being in the more openish areas and one in the toliet, but yeah I kept that in mind when doing this all, if it proves to be too much I'll end up changing it,but I want some variety in mobs and good spawns having robust defenses. But we'll see how it is if they get pushed to live

**Comment by UndeadNappist** [comment]
I'd like to request replacing the NCR, BoS, and gun store autolathe with construction lathes.
The BoS only have a circuit board of it.
**Leave the one in the Den alone.**
Add a constructionlathe to klamat.
Maybe shove an autolathe into one of the dungeons.

This is all optional, and it is a balance thing, but live map testing suggests it's a good idea.

**Comment by improvedname** [comment]
Will do undead requests in one of my prs when i touch vault

**Comment by Raze500** [comment]
>Not adding wintercoats mfw when ghostecho *cries in clothes*

**Pull request merged**
