### PR TITLE
MedX changes, associated minor chem nerfs

### PR DESCRIPTION
**Pull request by AdamElTablawy**
Ren's a retard so I just gave up and now med-x gives you 20% damage resistance to brute and burn while it's in your system it also does tiny amounts of toxin and it's addictive.

Legion medX has no changes.

Synthflesh now converts 66% of brute and burn to toxin damage if the mob it's used on is alive, to prevent synthflesh beakers being literally the absolute best healing chemical in the game.

Stypic and silver sulfadine no longer heal on touch at all, for much the same reason, but still heal over time.

Morphine has lost noslowdown for much the same reason-irrelevant since nothing uses it, but still. 

Ephedrine no longer speeds you up.
## Changelog (neccesary)
:cl:
del: Removed the effects of morphine and ephedrine
del: Removed stypic powder and silver sulfadine healing on touch (still heals over time)
tweak: Removed Synthflesh not converting 66% brute/burn into toxin when used on a LIVING person. Works the same as always for corpses. Still heals on touch.
balance: Med-X no longer removes slowdown. Instead, it increases damage resistance.
balance: Removed med-X not being instantly addictive, as it is now addictive no matter how much you take. It is also somewhat toxic.
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
One thing to note is that if you were to have 60 brute damage and then used a synthflesh patch or beaker you would still have 40 toxin damage. This would make synthflesh pretty much useless except for getting corpses back to defib.

If you can code it, I'd think a better solution to make the healing only 33% or 20% effective if applied by beaker so patches of these chems are useful, considering patches take time to apply.

**Comment by AdamElTablawy** [comment]
@Isy232 It's meant to be useless except for defibbing corpses.

**Comment by AdamElTablawy** [comment]
don't bother downvoting i don't care about feedback

**Comment by AdamElTablawy** [comment]
dawn of the final day i got feedback from ren and i'll fix the conflicts after this last day with that feedback unless someone has anything else they want to say that i'll ignore

**Comment by AdamElTablawy** [comment]
travis is a shit one sec

**Pull request closed without merging**
