### PR TITLE
Fixes role configuration

### PR DESCRIPTION
**Pull request by rhicora**
Head coders should be able to reply to tickets and help answer them.

### CODE REVIEW

**Comment by rhicora** [comment]
One of the root causes of the problem is that people who are actually primarily-dev staff but need +EVERYTHING are labeled "Game Master" and so people have admin-like expectations of them.

Hopefully this'll solve it.

**Comment by improvedname** [comment]
Yo fuck this aint a fix

**Comment by improvedname** [comment]
If you don't want to do admin stuff, then don't be an devmin and just a coder

**Comment by rhicora** [comment]
If you want to retire then don't use your unrevoked privileges on Github to remove labels.

**Comment by improvedname** [comment]
This ain't a bugfix, you are abusing the labels so im gonna remove said labels, closing PR due ignorance

**Comment by companoo** [comment]
imagine selfmerging

**Pull request merged**
