### PR TITLE
Slight Changes to NCR base

### PR DESCRIPTION
**Pull request by Hekzder**
## Description
Fences in the farm, adds some brahmin, removes excess pens, and replaces .45 with shotgun shell boxes instead.

## Motivation and Context
Farm needs brahmin, bramin need fences, too many pens, and .45 becomes useless since Captain is getting a Deagle. With Heavies, NCR now has four shotguns at start, so giving them some extra ammo is reasonable. 

## How Has This Been Tested?
Not tested super extensively but it is also only some small mapping changes. 

## Screenshots (if appropriate):
ncr farm

## Changelog (neccesary)
:cl:

add: Fence to the NCR farm.

add: Three brahmin to NCR farm.

del: Removed some excess pens around the NCR base camp.

tweak: Replaces the .45 ammo boxes in the NCR armory with buckshot boxes instead.

/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
>Ironically buffin NCR by decreasing the need of scavenging

**Comment by Cw3040** [comment]
>scavenging
>brahmin

**Comment by improvedname** [comment]
>Infinite FEV source
>Infinite Cheese source
>Infinite Virus food source(for the plants)
>not making a wooden barrel out of 30 wood

**Comment by JTGSZ** [comment]
I agree with @improvedname

**Comment by UndeadNappist** [comment]
You need to use the map merger. Also, ImprovedName is right. Go out into the wastes and collect.

**Pull request closed without merging**
