### PR TITLE
Pipes OOC chat and Ahelps to discord

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
## Description
Uses a flask webserver and discord webhooks to send OOC talk and adminhelps to discord.

## Motivation and Context
It doesn't really solve any problems, but it helps merge the game and the discord.

## How Has This Been Tested?
This is used on BeeStation (and was ported from there). It runs on a linux environment with Python 3.7, and the flask module installed.

It doesn't require linux to work however.

## Screenshots (if appropriate):
screenshot

## Changelog (neccesary)
:cl:
add: Added the ability to pipe ahelps and ooc to discord
server: added a python script that runs a flask webserver; required to send ahelps and ooc to discord
/:cl:

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
indentation died, hold on a sec

**Comment by LetterN** [comment]
i do like this, though tgs already has that as a feature

**Comment by CthulhuOnIce** [comment]
/shrug, I was asked to do this but if you guys have tgs it's cool

**Comment by GhostEcho** [comment]
This sounds hilariously awful but why is travis failing

**Comment by GhostEcho** [comment]
Oh its doing the dumb autistic shit it was doing earlier

**Comment by CthulhuOnIce** [comment]
This was forked from earlier code

**Comment by GhostEcho** [comment]
I

**Comment by CthulhuOnIce** [comment]
To test:
 
- set up webhooks on a discord server where you have permissions to do so

- set up the configs

- run the python script

- start the game server, connect, and start talking in ooc

**Comment by CthulhuOnIce** [comment]
There's a config in tools/discord where you need to put the webhooks, so it knows where to send data

**Comment by GhostEcho** [comment]
IT WORKS BOYS WOOOO

**Pull request merged**
