### PR TITLE
meth and salt gone

### PR DESCRIPTION
**Pull request by AdamElTablawy**
now you can't make meth or bath salts

### CODE REVIEW

**Comment by JohnOxford** [comment]
bad

**Comment by uzername** [comment]
Why?

**Comment by SpaceVampire** [comment]
This is awful even by your standards adem

**Comment by AdamElTablawy** [comment]
you know full well why

**Comment by JohnOxford** [comment]
very insightful
much convince

**Comment by ErwinSnowden** [comment]
bath salts are perfectly balanced because their brain damage is not nullified by mannitol and you will die if you take them without moderation.

you'll die easily if you eat more than 15u of bath salts the brain damage is that bad, otherwise i'm fine with meth removal since turbo exists.

**Comment by Hekzder** [comment]
This has been lingering around for a couple weeks, is probably not needed, let alone the fact that no one can really agree on whether or not this is good.

**Pull request closed without merging**
