### PR TITLE
Changes job hours

### PR DESCRIPTION
**Pull request by UndeadNappist**
Along with stripping out a few jobs (namely all the prime stuff, what the hell) this also lowers the required hours playtime for a lot of things.

It's been objectively demonstrated that it doesn't stop terrible players, it only acts as a temporary filter, and we've been having weird behavior where people pick a role then afk as it to open up higher slots.
## Changelog (neccesary)
:cl:
del: Removed heavy trooper and Prime stuff
tweak: Lowered job exp requirements
/:cl:

### CODE REVIEW

**Comment by RenGusta** [comment]
I'm not particularly pleased with this on the premise of removing an intermediary rank between recruit and veteran.

As per hours, the premise is to have people understanding their faction -WELL- before playing more important roles.

**Comment by Light-Weave** [comment]
>removed heavy trooper

lame

**Comment by UndeadNappist** [comment]
> I'm not particularly pleased with this on the premise of removing an intermediary rank between recruit and veteran.

Prime is explicitly above them in the text I yanked out, and according to the amount of required job experience before playing the higher roles.
With Centurion -> vet decan -> decan -> vex -> vet rec -> recruit -> scout -> explorer, there's enough granularity between the roles. The current issue is that there's too many legion so every round is a bloodbath usually resulting in legion victory due to there being about 15~ more job slots for them.
 
> As per hours, the premise is to have people understanding their faction -WELL- before playing more important roles.

People are afking and hiding places. Even captain in the original ss13 only requires 180 minutes. We're still way higher than that.

**Comment by RenGusta** [comment]
I'll get into some code reading before I come back to this with a follow-up: but the idea was that we could reserve veterans as a small group of high impact soldiers, instead of being 50% of the Legion.

**Comment by UndeadNappist** [comment]
Well, the job slots are correct, and so are some of the exp requirements.

**Comment by ScratKnapp** [comment]
Why the heavy trooper removal?

**Comment by companoo** [comment]
all of these changes are good lol

**Comment by GhostEcho** [comment]
Im holding this until Ren puts his final input

**Comment by Light-Weave** [comment]
we still don't have reasoning for removing heavies tho

**Comment by improvedname** [comment]
>removing heavies

**Comment by RenGusta** [comment]
Referring up the conversation, there was no described motivation for Removing Heavies, which at worse need a rework. Discussion in Balance Discussion occurred, resulting in the Prime Removal being unnecessary, as the slots are pretty close overall for NCR and Legion. I'm still completely okay with Hours reduction, regardless of personal misgivings.

**Comment by RenGusta** [comment]
Closing this for now, in case Nappist ever feels like coming back. I miss you, dad.

**Pull request closed without merging**
