### PR TITLE
Fixes pixel_x pixel_y for stuff in BoS base

### PR DESCRIPTION
**Pull request by JohnOxford**
a13675226a0b35403143bf694654a44e

### CODE REVIEW

**Comment by improvedname** [comment]
They are -32 for a reason so they don't appear on the wall from both sides

**Comment by improvedname** [comment]
Wait hold on why are you removing all fire alarms?

**Comment by improvedname** [comment]
Wait hold on why are you removing all fire alarms?

**Comment by JTGSZ** [comment]
hello, no. Those are dirty var edits, not movement breakers.

**Pull request closed without merging**
