### PR TITLE
removes buildable cyborgs from the bos

### PR DESCRIPTION
**Pull request by AdamElTablawy**
hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee hee

### CODE REVIEW

**Comment by Hekzder** [comment]
This just seems like a blatant, un-needed nerf to the BoS, along with removing something that there really aren't a lot of complaints about that is a rather nice mechanic to have around for getting ghosts back in to the game that doesn't involve them just respawning.

**Comment by AdamElTablawy** [comment]
consider the following:

cyborgs are very fast

illegal modules allow cyborgs to 1-hit-KO you

cyborgs are functionally infinite in number which goes against the bos' idea of small numbers

if the bos spawned with one cyborg i wouldn't protest it. infinitely buildable cyborgs, however, is a problem, especially when things like peacekeepers exist.

if i remove the things that make them, well, good, like illegal modules, peaceborg, and vtec, since they're also what makes them busted as well as good, then nobody will play it anymore as they suck as ghost roles.

**Comment by xeroxemnas** [comment]
Stupid grudge PR that literally no one asked for. Please go away Adam.

**Comment by AdamElTablawy** [comment]
why the hell would i care if anyone asked for this

**Comment by GhostEcho** [comment]
Just remove illegal modules for now

**Pull request closed without merging**
