### PR TITLE
Reworks RND materials, [WIP]

### PR DESCRIPTION
**Pull request by improvedname**
Reworks some material prices, to match up with tier prices.
I don't care what you say resources should count in a fallout based games.
So basically
10000 Diamonds will sound alot. but thats a tier 1 price.
Its 5000 At tier two.
2500 At tier three.
1250 At tier four.

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
that's still half a diamond sheet at tier 4 so doing this for items that need to be commonly printed would be terrible

fine for autosurgeons and shit tho

**Comment by ErwinSnowden** [comment]
10000 diamonds in one round will never fucking happen what's your fucking problem bro, how the FUCK am I supposed to get 10,000 diamodns honestly worst fucking change ever, i'm gonna lynch you

**Comment by improvedname** [comment]
Its called upgrading the manip partwhich halves the darn price.

THIS is tier 1 costs.
Tier 4 makes said 10000 diamonds a mere 1250 diamonds @erwinsnowdon so fuck off

**Comment by improvedname** [comment]
In short 1 diamond counts as 2000. The autoseurgeon will atleast cost 5 diamonds at tier one. 3 at tier 2 at tier 3 1 at tier 4

**Comment by rhicora** [comment]
This said WIP on it and should not have been merged until the author was ready!

**Pull request merged**
