### PR TITLE
Revert "Revert "re-ads erp""

### PR DESCRIPTION
**Pull request by JohnOxford**
Reverts BadDeathclaw/TG-Claw#779

02ed40e610f8f4c618566f96ced1befc
dd72ad678631dec6e79280df85bc8c8b
win

https://www.strawpoll.me/17778790/r

https://www.strawpoll.me/17778798/r

don't make us march on the capital.

### CODE REVIEW

**Comment by RenGusta** [comment]
What's this, using strawpolls without informing anyone you intend to use then, making then pretty much invalid?

Well played, John. Too bad it won't pass on premise. They rushed and they know it. Too bad they don't possess patience.

**Comment by JohnOxford** [comment]
908e5105d726c372323b19ba5f1a1758

**Comment by JohnOxford** [comment]
84 people is a pretty big chunk of the active playerbase ren

the balls in my court, your move.

**Comment by improvedname** [comment]
Use *me lol

**Comment by improvedname** [comment]
also can i point out how strawpolls are extremly vulnerable to vpn

**Comment by Logan-H** [comment]
It seemed to match up really close with the general attitude on the server, vote count and all.

**Comment by Tename** [comment]
Even if we consider half of the votes vpns only 30 people voted no.

**Comment by improvedname** [comment]
Only that aint reliable guess because vpn best case scenario is to get ren make a poll on the server itself but since we had major discussion fuck erp lol just use *me

**Comment by pireamaineach** [comment]
Is "just use *me" even an argument for the removal of E.R.P. verbs?

**Comment by improvedname** [comment]
>need snowflake low rp verbs because you cant be assed to type out erp

**Comment by pireamaineach** [comment]
I don't even E.R.P.
Seems pointless to remove.
If someone doesn't want to type out E.R.P., let them. You don't have to use the verbs if you don't like them.

**Comment by improvedname** [comment]
Seems pointless to have first place.
If somoene doesn't take the effort to type E.R.P don't add a snowflake verb for it. Verbs for minor things is just code bloat and uneccesary complexity.

**Comment by pireamaineach** [comment]
So because it's not up to your standards, remove it?
People clearly want it to stay.

**Comment by improvedname** [comment]
Silly boy
I have no standards

**Comment by ChronicPwnage** [comment]
I also don't ERP but don't see how it negatively affects the game. If players want it, give it to them. Who cares why? It doesn't hurt anyone else.

**Comment by JohnOxford** [comment]
local banned player who doesnt play the game enforces code standards

**Comment by JohnOxford** [comment]
local banned player who managed to only get banned on the discord enforces code standards*

**Comment by JohnOxford** [comment]
imagine a situation where only a select group of people in charge with no prior experience regarding the impact of the decisions they make, make a decision that affects the entire player base without informing or involving the player base whatsoever. 

then imagine those SAME people making the argument that the majority of the playerbase didn't want ERP. then when you call them out on it, imagine them just repeating the argument they already made regarding how they, within themselves, had a discussion about it

ghostecho

imagine having a "if you don't like it then fuck you" approach to development

but wait




heres the most important part



imagine articulating this to a large group of the player base, really in all honesty to everyone in general. explaining whats wrong about it and why it shouldn't be done and how the issue can be addressed in intricate detail without a small group of elitist individuals making all the decisions without the input of anyone else

then them basically saying "lol no fuck u big stupid"

just fucking imagine

**Comment by improvedname** [comment]
Lol no fuck u big stupid
You start sounding like one of oldmans novels to my ears already but instead of discussing water balance its why erp verbs should be reverted back when you have a perfect *me verb to accomplish everything you need. But no. "Me big lazy player. Me need stupid verbs which i can spam in a 100 times in a couple seconds because thats medium arphee also perfect esculattion hey guys lets go into a dorm room and just spam erp verbs the whole round :joy: lets make a swatzika stained in cum its fun guys. Lets cover the whole map in cum. ME LEGIONARY ME FUCK WOMAN TO REPRODUCE. thats your erp verbs mindset right here

**Comment by JohnOxford** [comment]
damn cant argue with that thanks hyena

**Comment by improvedname** [comment]
This isnt tg oxford accept that :shrug:

**Comment by improvedname** [comment]
And yeah i guess i am banned from discord but thats just for the bette

**Comment by pireamaineach** [comment]
"This isn't /tg/ so we're removing E.R.P. verbs."

If anything removing E.R.P. verbs makes this more like /tg/.

**Comment by pireamaineach** [comment]
Basically you're inconveniencing people because your standard of roleplay needs to be enforced on the entire playerbase even if they don't want it.

**Comment by improvedname** [comment]
>playerbase a.k.a the few people who use it.

**Comment by SpaceVampire** [comment]
So can't we just lower lust tolerance so you finish faster, and lower the rate you can click the buttons? I think we already had something like the second one in the re-adds ass slaps PR. That should go a long way towards fixing the spam issue.

**Comment by pireamaineach** [comment]
Why would you make people finish faster though?

**Comment by SpaceVampire** [comment]
The idea is that the total amount of time it takes to finish would be the same, you would just see less text popup.

**Comment by pireamaineach** [comment]
I mean. Wouldn't that really only be a problem if you could somehow INSERT several times by spamming the button? Just make it so you have to finish before pressing it again or something.

**Comment by JohnOxford** [comment]
here let me help you there

**Pull request closed without merging**
