### PR TITLE
Fixes headcoder rank having admin flags

### PR DESCRIPTION
**Pull request by improvedname**
Adminstration, and coding should be seperated 🤷‍♂️

### CODE REVIEW

**Comment by rhicora** [comment]
I don't see why this role should be _unable_ to answer player questions.

**Comment by improvedname** [comment]
Now you can.

**Comment by rhicora** [comment]
Now the main thing going on here is that Head Coders are no longer able to ban badly-behaved players if they see them. Is this really what we want?

**Comment by rhicora** [comment]
-AUTOLOGIN is fine and probably appropriate, coders should need to explicitly activate their powers.

**Comment by improvedname** [comment]
depends on Ren/Tea's view of coders doing adminstration work,

**Comment by improvedname** [comment]
Which brings me also on a idea for a new label

**Comment by UndeadNappist** [comment]
#696 figure it out

**Comment by Autismobirb** [comment]
I would rather not have it that /Coders/ do administration work, as it is not what they signed up for nor what me or Ren would like.

TL:DR CoDeRs NoT aDmInS

**Comment by companoo** [comment]
why would you want coders to be able to ban players lol

**Comment by improvedname** [comment]
Because the **headcoder questioned** it

**Comment by Raze500** [comment]
Why headcoders need the stuff of a admins do?  Literrally devs job is try to add new features/Fix bugs

**Comment by improvedname** [comment]
I asked for a code review, not a novel

**Comment by companoo** [comment]
devs should not be banning, they do not need +admin

**Comment by UndeadNappist** [comment]
Code review: it's not broken, you're not fixing anything, this is a snowflake role that belongs to one person who's never abused their position.

Removing it means fewer tickets will be answered.

Demands already handled in #696.

**Comment by improvedname** [comment]
C o d e r s aren't admins and neither was rhi

**Comment by improvedname** [comment]
And your more wrong about that nappist.

**Comment by UndeadNappist** [comment]
@improvedname
Please provide a rational, detailed argument, instead of just stating people are mistaken.

You were a devmin yourself.

**Comment by improvedname** [comment]
**All i can see here is Obvious coder clique playing off here**

**Comment by improvedname** [comment]
Because lets not forget nappist. that you spawned his grace somewhere in the wasteland, and a player got nearly ate for it. because you didn't bother to delete it as an coder

**Comment by improvedname** [comment]
And don't get me started on your previous coderbus, which you shouldn't have been doing.
Shitty bad gif imports into the game. breaking immersions… you know which im talking about nappist 
warned

warned you about the coder clique bro 👏

**Comment by improvedname** [comment]
In short that coders can't even be trusted with +spawn 🤔

**Comment by improvedname** [comment]
let stand +VV

**Comment by UndeadNappist** [comment]
His Grace was spawned in the last few minutes of the round, along with being put in a far corner of the map. I forgot to delete him. Oops.

The gif thing was hilarious, at a weird dead hour, and nobody actually complained about it as far as I know. People involved seem to enjoy themselves.

The problem is none of that has anything to do with me; the last time I was offered admin powers I declined.

Again, this has everything to do with you, and Rhicora. See previous statements.

Removing coder powers from server is a discussion for the alternative PR.

Finally, merging this one will cause conflicts. They're annoying.

**Comment by improvedname** [comment]
Merging this one would keep proper structure. as you and i know headcoders dont need to ban people.

**Comment by improvedname** [comment]
Looks like a headcoder stepping out her ranks 👅

**Comment by improvedname** [comment]
If this was a vendetta on you rhi, i would have done it way differently so stop assuming, headcoders dont need admin flags

**Comment by improvedname** [comment]
Have fun with your fucking coder clique im done.

**Pull request closed without merging**
