### PR TITLE
Who the hell thought this was a good idea

### PR DESCRIPTION
**Pull request by GhostEcho**
Alright, there needs to be a discussion on how much shit people throw into one PR

### CODE REVIEW

**Comment by Light-Weave** [comment]
1) commenting the speedloader out is gonna break shit because the speedloaders actually existed already
and 2) the sequoia does terrible damage anyway because -20 AP, just increase the cost or something- right now it's worth 1.5x a .44 speedloader but we could make it 2x (plus the 2x multiplier from the ammobench being inefficient) = 8-10 sheets 

having uncraftable ammo is dumb when the ammo sucks

**Comment by JTGSZ** [comment]
Hello, for some future advice try using ctrl +f.
Untitled

**Comment by Light-Weave** [comment]
update: we came to a SUPER COOL conclusion in the discord (craftable .45-70 lowpower) so 
take this PR down and I'll fix the recipe in the upcoming 4570LP PR

**Comment by GhostEcho** [comment]
Indeed @Light-Weave talk with Ren about it though and work with him for numbers

**Pull request closed without merging**
