### PR TITLE
Anti-Materiel Rifle

### PR DESCRIPTION
**Pull request by Light-Weave**
**This is not the syndicate anti-materiel rifle. That one's hilariously OP. I'm not touching it.**

## Description
Adds the .50 MG anti-materiel rifle from Fallout: New Vegas, chambered in a new .50 MG round (not to be confused with .50 AE, used for deagles). NCR Veteran Rangers spawn with this gun, and ammo is available in autolathes.

4+1 shots, and recoil and a substantial fire delay. Shots must be loaded one bullet at a time.

.308 ammo (scoped Remington, Rangemaster, etc): 40 damage, 20 AP. 7,000 metal cost.
.50 MG ammo: 50 damage, 20 AP. 14,000 metal cost.
.50 MG/Incendiary: 30 damage, 0 AP, buuuut it sets them on fire, so... 20,000 metal cost.
.50 MG/AP: 35 damage, 65 AP. Will punch through any armor like wet tissue paper. 18,000 metal cost.

So what does this mean for typical conflicts? Short version, it means it's more effective than the .308's at taking down lightly-armored targets with standard rounds (Recruit Legionaries, Raiders) or extremely heavily-armored targets with AP rounds (BOS power armor).

It does kick like a mule, though, so if you're hoping to snap off rapid shots like with the Remington, you better have good aim.

Compared to a scoped Remington:
+ More damage! You can now two-shot Recruit Legionaries.
- Slower rate of fire, which means your TTK is slower, but who cares? You've got...
+ Incendiary bullets! Which set fire to whoever they hit.
- They don't do much damage, though, especially against armored targets...
+ ... which is fine, because you have AP ammo for cracking the big nuts.
- Or you would, if you could get some, because all this costs a fortune in metal from the lathe.
+ But hey, it's worth it, 'cause you get the prestige of having a cool gun.
- And the lower ammo count, and the recoil..

## Motivation and Context
You know how Veteran Rangers spawn with a scoped Remington, an alarmingly common gun that really doesn't match their prestige at all? Well, now they get something cool. It's a little stronger, a lot rarer, and it's shiny as hell. Ammo is hard to come by and expensive, but you can scope in and drop some deathclaws like nobody's business. Oh, and you look dope as hell doing it.

The Vet Ranger's gun is currently *less cool* than the Patrol Ranger's gun. This fixes that. It's the Sequoia of rifles- the Veteran Ranger can now go toe-to-toe against the BOS Paladin and stand a chance. (You know how much damage a Sequoia does to T-51b power armor? **10.8**. Go get some AP rounds if you're taking on the Brotherhood.)

## How Has This Been Tested?
Fully tested, including autolathe spawning and different ammunition types.

[Balance, 24h hold] [Feature, 24h hold]

## Changelog
 :cl: Light-Weave
add: Adds the anti-materiel rifle, along with regular, AP and incendiary ammo for it.
add: NCR Veteran Rangers spawn with the AMR, and more ammo can be made in autolathes.
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
this only supports vet ranger vigilante

**Comment by Light-Weave** [comment]
They'll learn their lesson when someone bolas them and shoots them with their own AMR. It's kinda like the NCR equivalent of the Machete Gladius or the tri-laser. (Sequoia doesn't count because -20 AP and limited ammo is terrible and we all know it.)

**Comment by JohnOxford** [comment]
bastard you beat me to it

**Comment by JohnOxford** [comment]
#731

**Comment by Light-Weave** [comment]
Requires merging #731 to pass Travis checks.

**Pull request merged**
