### PR TITLE
Job exp system

### PR DESCRIPTION
**Pull request by LetterN**
does work, DB screenshot bellow 

image

### CODE REVIEW

**Comment by AndrewL97** [comment]
Does this require any config on the server? If not, happy to smash this in and update today

**Comment by LetterN** [comment]
the config changes are already in there, also admins can bypass this, and admins can select people to bypass it also.

**Comment by AndrewL97** [comment]
siq

**Comment by AndrewL97** [comment]
Bonus points for screenshot

**Pull request merged**
