### PR TITLE
Replaces default metal wall sprite with a new corrugated metal wall sprite.

### PR DESCRIPTION
**Pull request by GoodG1448**
I personally dislike the look of the default metal wall in this setting, I decided to make it look like corrugated metal since it fits with the post-nuclear aesthetic.

The walls look like this in game:
reference final

### CODE REVIEW

**Comment by GhostEcho** [comment]
Are we Eris now? Think they could use a little more work, seems a little off

**Comment by GoodG1448** [comment]
Blame it on how the wall sprites link with each other in TG. You want them thicc-er like this?

thicc

**Comment by GhostEcho** [comment]
Its how the corners just go into triangles

**Comment by GoodG1448** [comment]
By looking at how wall textures link in the new map, I will guess that it will conflict with the new sprites in the new map. Closing until all the map merges and stuff are ready and set.

**Pull request closed without merging**
