### PR TITLE
Resprites (almost) every gun in the game

### PR DESCRIPTION
**Pull request by JohnOxford**
## Description
- Edits the structure of the sprites to be slightly better in some cases, uses the same 4 shades of wood and 9 shades of metal for every gun for consistency in color and in art style 
- Adds sprites for a hunting shotgun
- Adds Gauss rifle sprites that actually look like a Gauss rifle.
- Adds crossbow sprites
- Makes all the revolvers a consistent size, with the exception of vanilla revolvers
## How Has This Been Tested?
with my eyes

## Screenshots (if appropriate):
b0628bbec9cc4a014f9c4d68463a6598

## Changelog (neccesary)
:cl:
add: Added new sprites for (most) guns
/:cl:

### CODE REVIEW

**Comment by waterwater1212** [comment]
add more gun w/ silencer sprites

**Comment by JohnOxford** [comment]
additionally, in order for me to actually add the weapons for the sprites i've added here, that being the crossbow, hunting shotgun, and gauss rifle, i need the other PR changing the names to be consistant merged 

the day i create my own merge conflicts is the day i kms

also ye git right on that

**Comment by waterwater1212** [comment]
thanks bro

**Comment by JohnOxford** [comment]
- 9mm pistol doesn't have a threaded barrel
- uzi is silenced
- you can't silence revolvers (ask me about the nagant revolver in discord)
- Mosin Nagant doesn't have a threaded barrel
- hunting rifles look retarded with either a 2 pixel long """""suppressor"""" which is really just a 3 pixel tall rectangle at that point, or they look retarded when you have to squish the rifle to fit the suppressor. so for sake of convince we'll say they just don't have threaded barrels
- shotgun suppressors exist but i dont see them having a place on traditional shotguns and certainly not on double barreled shotguns
- gauss rifle can't be silenced, it doesn't emit gas.

long guns are innately difficult to sprite with a suppressor on them that doesn't look like absolute fucking garbage. the infiltrator is the exception because it doesn't have a stock (more room for the suppressor)

everything else is already silenced

the guns that people keep putting suppressors on and it makes them invisible or doesnt change the sprite probally shouldn't have suppressors on them in the first place. its a coding oversight that i'll fix when i go to add the guns that i made sprites for

**Comment by waterwater1212** [comment]
infiltrator has a built in silencer and i want shotgun silencers or else... You've been warned, John Oxford.

**Comment by JohnOxford** [comment]
"silencer"

im removing suppressors in my next pr

you should feel bad

waterman

**Comment by waterwater1212** [comment]
how about i silence your fucking screams with a pillow as i stab you to death, John Oxford?

**Comment by JohnOxford** [comment]
this message has been brought to you by

SilencerCo™

bringing out the homicidal tendencies in us all since 2004

**Pull request merged**
