### PR TITLE
[READY] Makes Veteran Rangers look mildly better.

### PR DESCRIPTION
**Pull request by pireamaineach**
New:
RangerNew
Old:
VeteranRangerOld

:cl:
add: Added the rifleman's gloves.
add: Added the laced boots.
add: Added the veteran ranger outfit, more like the one seen in the game.
fix: Made the .45 magazine actually swap sprites appropriately rather than just showing full or empty. (Was dicking around in the magazine files and noticed while making this P.R.)
fix: Readds the vault sprite changes that were supposed to be made when https://github.com/BadDeathclaw/TG-Claw/pull/824 was merged. (Not originally intended to be part of this P.R. but there happened to be a merge conflict that brought this to my attention.)
tweak: Veteran Rangers now spawn with a veteran ranger outfit, NCR duty belt, rifleman's gloves, and laced boots.
imageadd: Tweaks the Ranger combat armour's sprite.
/:cl:

### CODE REVIEW

**Comment by pireamaineach** [comment]
Going to go ahead and fix the shit I messed up by being a dumb ass while fixing merge conflicts.

**Comment by companoo** [comment]
imagine walking long distances in the desert in laceup shoes

**Comment by pireamaineach** [comment]
Just the closest thing to what is seen in game. They're probably more like trainers if you want me to use sneakers.
Plus jackboots are less than practical anyway.

**Comment by pireamaineach** [comment]
The entirety of the legion has gloves with armour though.

**Comment by pireamaineach** [comment]
Yeah that's an exact mirror of the legion's gloves' armour. I added it because the concept art I was using had armour plating on the gloves.

**Comment by GhostEcho** [comment]
Keep in mind the vet ranger coat covers arms and already has 70 melee resist

**Comment by pireamaineach** [comment]
Youch.

**Comment by GhostEcho** [comment]
my only request is to remove the armor from the gloves because while yes its just two limbs, it brings up the armor on those limbs in the 80%

**Comment by pireamaineach** [comment]
Done.

**Comment by GhostEcho** [comment]
Blessed

**Pull request merged**
