### PR TITLE
Update simple_animal.dm

### PR DESCRIPTION
**Pull request by UndeadNappist**
It's literally one variable guys, yikes. #597

### CODE REVIEW

**Comment by Autismobirb** [comment]
If the number is raised that high there is no point having that section of code, servers wasting time counting chickens.

For the time being the simple request was to remove this section for the time being, much like Rhi had done in #597

**Comment by UndeadNappist** [comment]
One extra NPC is more for the server to keep track of than a single counter.

**Comment by rhicora** [comment]
This looks fine from a code standpoint.

**Comment by improvedname** [comment]
But can you edit the var?

**Comment by rhicora** [comment]
@Autismobirb I think there's a fair case for having the mob limit as a sanity test; if someone is spamming cows / slimes to the point where it starts to drag on the server, we should stop it at some stage.

**Comment by UndeadNappist** [comment]
If the limit gets hit again and is irritating, it can be raised again. This also coupled some code cleanup with it.
My major concern is that someone __will__ - And I don't mean might, the server is up for 24/7 - eventually cause a slimepocalypse or something else equally low tier and ridiculous, given that they scale geometrically.

**Pull request merged**
