### PR TITLE
Loadout Selector

### PR DESCRIPTION
**Pull request by NanakoAC**
Adds a loadout selector to the game which allows players to choose additional equipment post-spawn.

Loadouts are setup by adding outfits to the loadout_options list on job datums. Any outfit works

Video of system in action
https://drive.google.com/file/d/1QADdJ3qj8bRTOcmtWKtqL-jyeZhM9wtX/view?usp=drivesdk

Players whose role has additional options will be notified with a message in chat, and given a loadout selector token which can be activated to open the menu. This token can't be dropped and will delete itself once an outfit is picked. Select Loadout verb is also added to the IC menu, and this goes away once loadout is picked too.

The selected items are spawned into a box and placed in the player's hands. This is an entirely normal box and the items will generally not fit back into it once removed, since you're getting entire suits of armor+helmets

### CODE REVIEW

**Comment by Arkatos1** [comment]
Just a heads up, this PR currently reverts Great Khan role back to a Pusher role, and makes it so they wont even start in a Great Khans gang, making their whole faction unobtainable ingame.

**Comment by NanakoAC** [comment]
> 
> 
> Just a heads up, this PR currently reverts Great Khan role back to a Pusher role, and makes it so they wont even start in a Great Khans gang, making their whole faction unobtainable ingame.

because of modifications to the wasteland file?
I'll try to fix it

**Comment by Arkatos1** [comment]
@NanakoAC I looked into it, and I think so. I would recommend reverting that last commit, from what I have seen, problem was that in khan selector loadout option for raiders. Pushers were transformed into Great Khans, and all khan items were removed from the raiders and given exclusively to Great Khans, so khan selector loadout conflicted.

**Comment by NanakoAC** [comment]
First of all, Am i targeting the correct branch?

I've tried merging and rebasing master, no conflicts, things seem identical

**Comment by NanakoAC** [comment]
Fixed, latest commit should sort everything

**Comment by Arkatos1** [comment]
Looks good, thank you.

**Pull request merged**
