### PR TITLE
Decreases oxyloss, increases crit amount

### PR DESCRIPTION
**Pull request by UndeadNappist**
Does what it says on the tin.

#1166

### CODE REVIEW

**Comment by CameronWoof** [comment]
Increasing the damage needed to kill someone by 50% is a large balance change that shouldn't be part of this PR. Take just the reduced oxy loss for now and start doing other stuff after.

**Comment by UndeadNappist** [comment]
This PR probably doesn't go far enough to do all the things I want it to do, and likely isn't sufficient enough in all the alterations.

"Because it is a large balance change" is an insufficient argument to deny something.

cross-ref;
https://github.com/BadDeathclaw/TG-Claw/pull/283
https://github.com/BadDeathclaw/TG-Claw/pull/612

**Comment by CameronWoof** [comment]
I'm not saying a PR can't contain a large balance change, but this one contains two. You've tripled the time it takes to die from being in critical condition and THEN doubled that in the same PR. Take the first change on its own and see if that's enough. At that rate, *any* healing should be enough to reverse the brute/burn faster than the oxyloss mounts.

**Comment by UndeadNappist** [comment]
No, I've cut oxy damage from not having sufficient oxygen by a third, and doubled the amount of damage you have to take in crit before dying.

Bloodloss is still an ongoing and unchanged issue.

It's not the same as "tripled the amount of time it takes to die in crit."

**Comment by CameronWoof** [comment]
You will absolutely die of crit oxyloss before you bleed out, even with this change. "It takes six times longer to die" is very accurate.

**Comment by UndeadNappist** [comment]
https://github.com/BadDeathclaw/TG-Claw/blob/d6ffeb207849abcc3d993d4326ee0cef6c9c1a73/code/modules/mob/living/blood.dm#L54

Bloodloss straight up adds oxyloss damage, which is not so much of a bad thing when you aren't already suffocating. This is likely why people are dying so fast in crit, and why it seems to scale up so quickly.

BLOOD_VOLUME_NORMAL is 560
BLOOD_VOLUME_BAD is 224, which is where you start taking oxyloss
BLOOD_VOLUME_SURVIVE is 122, which is where you start having chances to have heart failure and insta-die.

bleed_rate varies
https://github.com/BadDeathclaw/TG-Claw/blob/d6ffeb207849abcc3d993d4326ee0cef6c9c1a73/code/modules/mob/living/blood.dm#L76
but essentially the number of times you are hit directly impacts how fast you bleed out and how fast you take oxy damage.

It will not take six times longer to die due to this game's method of scaling how fast you die in crit upwards.

**Comment by CameronWoof** [comment]
In current code, dying by bleeding out (drop into soft crit after being shot three times with a .308 rangemaster) takes between four and five minutes, as I just tested. That speed is hastened by the three oxyloss per tick of falling into hardcrit. 

Keep in mind, I died due to oxyloss, not heart failure, at over 400u of blood.

This PR, in its current state, will make that slow, inexorable slog to death take even longer. This *will not be fun*. Put the death mark back at -100 and this PR will be much less annoying to deal with.

**Comment by UndeadNappist** [comment]
You can instantly die whenever you want from typing succumb. There is no slog. It's just a faint sliver of hope.

This is to make kidnapping people easier and keeping certain niche storylines open, as I said in my open issue. It is unrelated to people dedicated to killing each other.

**Comment by GhostEcho** [comment]
You can also ghost as well or *deathgasp to succumb(if youre in deep crit), so the slog of dying isnt relevant, but im curious on Rens thoughts

**Comment by RenGusta** [comment]
It was discussed in VC which is why he actually made the PR, dingus

**Comment by CameronWoof** [comment]
This was the last thing mentioned, I said "I don't like the sound of that," and then no further conversation was made. I'm offering my feedback.

**Comment by AdamElTablawy** [comment]
Good thing nobody cares since your feedback is without value

**Pull request merged**
