### PR TITLE
removes degeneracy (removes spraytan)

### PR DESCRIPTION
**Pull request by JohnOxford**
spray tans don't exist in the map outside of loot tables so this actually doesn't affect the map

this also completely removes it instead of just breaking it

fucking rhi

### CODE REVIEW

**Comment by JohnOxford** [comment]
speed merge or bust

**Comment by rhicora** [comment]
Remove reaction entries please. https://github.com/BadDeathclaw/TG-Claw/blob/master/code/modules/reagents/chemistry/recipes/others.dm#L14

**Comment by JohnOxford** [comment]
all this effort in the name of a good clean christian server

**Comment by JohnOxford** [comment]
04bca860e6078a7f597453e387331d6b

**Comment by JTGSZ** [comment]
Who spray-tanned you to cause such a knee-jerk reaction?

**Comment by UndeadNappist** [comment]
@JTGSZ https://github.com/BadDeathclaw/TG-Claw/blob/master/code/modules/reagents/chemistry/reagents/other_reagents.dm#L411

**Comment by JohnOxford** [comment]
gotta remove it from lavaland ruins hang on

also a fucking heretic spray tanned me such crimes are unacceptable

**Comment by JohnOxford** [comment]
i think this just broke the shit out of it but we'll see

**Comment by skateboardjones** [comment]
Could remove the overdose. Some people use it for disguises or self-torture.

**Pull request merged**
