### PR TITLE
N.C.R. dog tag sprite changes.

### PR DESCRIPTION
**Pull request by pireamaineach**
The current sprites are too big, and the way it's perfectly upright is off-putting.
:cl:
tweak: Resprites N.C.R. dog tags based off of the holotag sprite.
/:cl:

### CODE REVIEW

**Comment by companoo** [comment]
is this ever getting merged lol if theres no issues?

**Comment by Hekzder** [comment]
This is mostly just un-needed and Senior, the original creator of the dog tag sprites, was spoken to regarding this and said he doesn't want to see this PR go through, IIRC. 

Now that there's action on this PR again then I may close it in the next day or two if the author doesn't speak up regarding it, because I believe they are inactive as of now.

**Comment by pireamaineach** [comment]
What?

**Comment by companoo** [comment]
they are active as of now

**Comment by pireamaineach** [comment]
This getting merged ever?

**Comment by Hekzder** [comment]
Most likely not, I've spoken with Senior, the person who originally made the dog tag sprites, and he doesn't want the sprites to be changed. Apparently Ren has said that as long as he doesn't want the sprites changed then this will not be merged.

**Comment by pireamaineach** [comment]
Okay, why isn't that standard help up with my sprites?

**Pull request closed without merging**
