### PR TITLE
Armor 2: Electric Boogaloo Redo

### PR DESCRIPTION
**Pull request by Karl-Franz-I**
## Description
Overhaul of a lot of armor:
NCR;
Recon Duster gets less melee protection but a good increase to bullet protection.
Veteran Ranger armor/helmet also gets nerfed melee protection but increased bullet protection.
Desert Ranger/Elite Riot Armors/helmets gets buffs across the board to scale with Veteran values.
Recon/Patrol Ranger hats get a large buff.
NCR Recruit/Trooper helmets are buffed.
NCR Sergeant/Lieutenant/Captain berets now have decent armor.

Legion;
Buffs Legate helmet to match the chest armor.

Neutral;
Significantly buffs bone armor melee protection, makes it less viable for ranged warfare.

Overhaul:
After discussion with Ren: armor has been removed from gloves and boots, which was complicating balance. Instead, most armors now provide full coverage of chest, groin, legs, and arms.

## Motivation and Context
General lack of balance, some inconsistencies, fixing NCR armor being left in the dust a long time ago while Legion only got stronger. 

## Changelog (neccesary)
:cl:
balance: Rebalances most NCR headgear, NCR ranger armors, bone armor, bracers, and skull helmet.
tweak: Legate helmet values
/:cl:

### CODE REVIEW

**Comment by SeniorScore** [comment]
Based and Bonepilled

**Comment by Karl-Franz-I** [comment]
> Based and Bonepilled

Badda bing badda bone bracers

**Comment by pireamaineach** [comment]
Why lower melee protectron for bullet protection? Most combat I get into as ranger has a heavy focus on melee.

**Comment by Karl-Franz-I** [comment]
> Why lower melee protectron for bullet protection? Most combat I get into as ranger has a heavy focus on melee.

Because the NCR has always had the ranged advantage. Multiple men in a group firing together totally shreds legion troops (Who have high melee protection and lower bullet protection). You then have even more men, like rangers, firing from offscreen in support of your fellow soldiers. NCR armor is not made for going toe-to-toe in CQC with legionnaires. I gave higher bullet protection and lower melee because the two factions are supposed to have opposite fighting styles. The legionnaire tries to get close to you and you shoot him dead. The legionnaire tries to shoot you, but you tank his damage with your superior ranged armor and shoot him dead. You should be worried if you miss all your shots and he gets right up in your face.

**Comment by pireamaineach** [comment]
Except rangers actually are intended to have skills in CQC. When they're whitelisted they're supposed to actually get CQC as an ability. Also the example you provide has literally never happened, it would require 1. Organised N.C.R. or 2. Dumb legionnaires rushing the N.C.R. base without a plan.

**Comment by Karl-Franz-I** [comment]
> Except rangers actually are intended to have skills in CQC. When they're whitelisted they're supposed to actually get CQC as an ability. Also the example you provide has literally never happened, it would require 1. Organised N.C.R. or 2. Dumb legionnaires rushing the N.C.R. base without a plan.

Yes...once they get whitelisted I am the one giving them CQC. Also, the example I provided happens to me all the time from both sides as I play legionnaire and ranger/trooper. It also isn't just defensively, myself and a few rangers have shredded 5 legionnaires before they got into melee range on the road after proper escalation. You can also wordlessly shoot legion from offscreen if they are already engaged with other NCR troops. Rangers are a robust supporting role that most people don't use to their best effect. Regarding their close quarters skills, this is for rangers who aren't whitelisted, these values will most likely be changed once the rangers are overhauled. Also note that legionnaires are just as physically fit as rangers, and also savage in unarmed and melee combat, posing a threat to even rangers when they get close, if we look at lore. Even if they got CQC training right now, that has no correlation, and doesn't magically make their armor more protective. The veteran ranger melee protection in this PR is STILL second only to centurion and power armor; and the Recon Duster is still a leather jacket with more protection than standard NCR armor.

**Comment by AdamElTablawy** [comment]
This makes reinf combat armor < vet ranger armor, incidentally.

**Comment by Karl-Franz-I** [comment]
Just checked, it makes them equal in melee protection, yes. As one is a pre war reinforced US army armor and the other is also pre war law enforcement armor. The combat armor has better laser protection, the Vet armor has more bullet protection and covers the entire body.

**Comment by AdamElTablawy** [comment]
Right, and the covers the entire body thing won't be exclusive shortly (hopefully.)

The vet armor has better bullet protection, but it's gone down from taking 12 machete hits to crit a ranger to 9, for a comparatively minor hits-to-crit for standard bullet fire.

So, I dunno, a loss of four extra hits is painful.

**Comment by RenGusta** [comment]
Going to have to remove the armor from the NCR subtype of boots you made. Also going to have to adjust all the icons and shit another day, but that's for then.

**Comment by Karl-Franz-I** [comment]
Bruh, those boots dont exist anymore, I PMed you about how I changed it to what you wanted and to merge

**Pull request merged**
