### PR TITLE
Ranger Outpost Golf

### PR DESCRIPTION
**Pull request by Light-Weave**
## Description
NCR Rangers now spawn at Ranger Outpost Golf, far to the southeast of the Den. Enjoy.

## Motivation and Context
Rangers are traditionally not-quite-NCR-soldiers, so they don't spawn with the rest of the NCR. Ranger Outposts are a *Thing*- oh, and Alpha through Foxtrot are already taken.

## How Has This Been Tested?
It's a map PR, but I tested it anyway.

## Screenshots (if appropriate):
https://cdn.discordapp.com/attachments/453657584701014047/563501024552419338/unknown.png

## Changelog (neccesary)
:cl:
add: NCR Rangers now spawn at Ranger Outpost Golf, to the southeast of the Den.
/:cl:

### CODE REVIEW

**Comment by ScratKnapp** [comment]
Pics?

**Comment by companoo** [comment]
need pics and it also conflicts

**Comment by Light-Weave** [comment]
Uuuuughhhhhhhh fixing it now

**Comment by Light-Weave** [comment]
goddammit travis

**Comment by Light-Weave** [comment]
stand by, travis is an asshole and merge conflicts are hell on earth

**Pull request closed without merging**
