### PR TITLE
Ghoul sprites

### PR DESCRIPTION
**Pull request by DIamonnd**
## Description

Adds the firstly intended sprites for ghouls, male and female sprites having differences on chest (as the human ones do.)
## Motivation and Context

Don't know, is the first idea shit.
## How Has This Been Tested?

Just start up the game and different clothings, is just a sprite change.
## Screenshots (if appropriate):
female
male
ranger
sheriff

### CODE REVIEW

**Comment by Raze500** [comment]
Greyscale works?

**Comment by Raze500** [comment]
Add this 2 var in ghoul.dm

`default_color = "FFFFFF"`
`use_skintones = 0` 

I want know beacuse im coding on ghouls too hah.

**Comment by DIamonnd** [comment]
Ima try so when I can, gonna make a wild guess and say it may be possible but for how they are rn may not work

**Comment by DIamonnd** [comment]
Did it, nothing changed, litterally nothing.

**Comment by improvedname** [comment]
will conflict with #642

**Comment by Raze500** [comment]
@Dlamonnd Remove sexes = 1 to 0 i will add the 1 in my pr :)

**Comment by DIamonnd** [comment]
@Raze500 Aigthy, done.

**Comment by improvedname** [comment]
Edited the sex changes away as its being handled in raze's pr to avoid conflict

**Pull request merged**
