### PR TITLE
Hotfixes for constructionlathe and whispering in crit/softcrit/hardcrit

### PR DESCRIPTION
**Pull request by UndeadNappist**
An ugly fix for constructionlathe, and me being stumped by spaghetti for say for awhile.

It works properly now.

### CODE REVIEW

**Comment by UndeadNappist** [comment]
https://github.com/BadDeathclaw/TG-Claw/blob/master/code/modules/mob/living/living.dm#L268

https://github.com/BadDeathclaw/TG-Claw/blob/master/code/modules/mob/living/say.dm#L173

I hate the ss13 coders sometimes.

**Comment by UndeadNappist** [comment]
As I said, ugly fix. Yes. The other method is more fiddly - reassigning the techweb vars or mucking about with even worse spaghetti.

I just set security items to !can_build

**Comment by JTGSZ** [comment]
Are you completely fine with it being like this?

**Comment by UndeadNappist** [comment]
Yes. It makes it match the description of the constructionlathes, which amuses me.

I'll get around to something other than a hotfix later.

**Pull request merged**
