### PR TITLE
ERP Fix+Add. New Verb.

### PR DESCRIPTION
**Pull request by MrBobCool**
## Description
Fixes some ERP verb typos, and color of text.
Adds the new verb, "Ass Grope/Grope Ass". _Because why not be able to grope someones tits but not their ass?_
**REMOVED DUE TO REQUEST:** Adds a **'foundation'** for CBT verbs (CBT verbs is a community request. Everyone wishes for it to be locked behind a book, I would continue working on it but I got other things to do.)
Adds some sound to a verb that had no sound.
Made throat fucking do a more oxygen damage.
You can now, bite someones ass on harm intent if they're doing verb;'ass to face'.

## Motivation and Context
Being banned.

That and degeneracy.

I was bored.

## How Has This Been Tested?

Private server, 'cult ghost' dummy.

**NOTE:** Don't try to use verbs on the 'Carbon/human/Dummy' or whatever, because the anti-verb spam/cooldown is broken with it for some odd reason.

## Changelog (neccesary)
:cl:
add: Added new things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
code: changed some code
/:cl:

_Degenerates like me belong on the cross._

### CODE REVIEW

**Comment by Hekzder** [comment]
I don't really know why your PR consists of deleting everything and then re-adding it. Also CBT verbs are a meme. If those two things are fixed I'll consider approving this.

**Comment by MrBobCool** [comment]
> I don't really know why your PR consists of deleting everything and then re-adding it. Also CBT verbs are a meme. If those two things are fixed I'll consider approving this.

You never stated to fix anything. The PR deletes everything and then re-adds it for no reason. It probably is doing this due to the fact I had to indent and change the ways of some things. This causes no errors. CBT isn't added yet, there's nothing to delete. I just made a; **'foundation'** for it.

**Comment by Hekzder** [comment]
> > I don't really know why your PR consists of deleting everything and then re-adding it. Also CBT verbs are a meme. If those two things are fixed I'll consider approving this.
> 
> You never stated to fix anything. The PR deletes everything and then re-adds it for no reason. It probably is doing this due to the fact I had to indent and change the ways of some things. This causes no errors. CBT isn't added yet, there's nothing to delete. I just made a; **'foundation'** for it.

Deleting and re-adding everything makes it an eye sore and annoying to see what was actually added and/or changed. CBT verbs are something I don't want to be indulged, even a foundation I am opposed to.

**Comment by MrBobCool** [comment]
> > > I don't really know why your PR consists of deleting everything and then re-adding it. Also CBT verbs are a meme. If those two things are fixed I'll consider approving this.
> > 
> > 
> > You never stated to fix anything. The PR deletes everything and then re-adds it for no reason. It probably is doing this due to the fact I had to indent and change the ways of some things. This causes no errors. CBT isn't added yet, there's nothing to delete. I just made a; **'foundation'** for it.
> 
> Deleting and re-adding everything makes it an eye sore and annoying to see what was actually added and/or changed. CBT verbs are something I don't want to be indulged, even a foundation I am opposed to.

I told everything that's changed in the description. Nothing I changed should effect other coders. Nor will the CBT. I don't really see the problem here.

**Comment by Hekzder** [comment]
> > > > I don't really know why your PR consists of deleting everything and then re-adding it. Also CBT verbs are a meme. If those two things are fixed I'll consider approving this.
> > > 
> > > 
> > > You never stated to fix anything. The PR deletes everything and then re-adds it for no reason. It probably is doing this due to the fact I had to indent and change the ways of some things. This causes no errors. CBT isn't added yet, there's nothing to delete. I just made a; **'foundation'** for it.
> > 
> > 
> > Deleting and re-adding everything makes it an eye sore and annoying to see what was actually added and/or changed. CBT verbs are something I don't want to be indulged, even a foundation I am opposed to.
> 
> I told everything that's changed in the description. Nothing I changed should effect other coders. Nor will the CBT. I don't really see the problem here.

The problem with CBT verbs is something I've already stated, I don't want to indulge this personally and it's something that unironically should be talked about before being added, in my opinion. There is not some kind of massive community uproar for CBT verbs, it's mostly just Techno and a few others memeing about it. 

Additionally, it's annoying for me to actually verify that you only changed what is in the description because you have deleted and re-added everything, according to the file changes that I can see.

As I've already told you, remove the CBT verbs and fix the file change parts of this and I'd have very little issue with approving this PR.

**Comment by MrBobCool** [comment]
There, removed the CBT. I can't fix the 'delete all and readd' due to it most likely being causes by indentation. I've not once deleted everything and readded it during coding. Don't know what else to say.

**Comment by Hekzder** [comment]
> There, removed the CBT. I can't fix the 'delete all and readd' due to it most likely being causes by indentation. I've not once deleted everything and readded it during coding. Don't know what else to say.

If it's an indentation problem then please fix the indentation problem, again, it's more so just the standard of it all than anything else. It's hard to verify your PR due to this _and_ I don't want people to start thinking it's allowed to change entire files to hide small, hidden changes. Not fixing this and having it merged like this will set that precedent.

**Comment by MrBobCool** [comment]
> > There, removed the CBT. I can't fix the 'delete all and readd' due to it most likely being causes by indentation. I've not once deleted everything and readded it during coding. Don't know what else to say.
> 
> If it's an indentation problem then please fix the indentation problem, again, it's more so just the standard of it all than anything else. It's hard to verify your PR due to this _and_ I don't want people to start thinking it's allowed to change entire files to hide small, hidden changes. Not fixing this and having it merged like this will set that precedent.

There _isn't_ a way to fix this that I know of. Feel free to share a way to fix it with me. There's not indentation 'problem' it was more of a fix to add more code.

**Comment by Hekzder** [comment]
> > > There, removed the CBT. I can't fix the 'delete all and readd' due to it most likely being causes by indentation. I've not once deleted everything and readded it during coding. Don't know what else to say.
> > 
> > 
> > If it's an indentation problem then please fix the indentation problem, again, it's more so just the standard of it all than anything else. It's hard to verify your PR due to this _and_ I don't want people to start thinking it's allowed to change entire files to hide small, hidden changes. Not fixing this and having it merged like this will set that precedent.
> 
> There _isn't_ a way to fix this that I know of. Feel free to share a way to fix it with me. There's not indentation 'problem' it was more of a fix to add more code.

I'm not 100% sure what the issue is, therefore helping you with a fix is hard. Worst thing is you could simply just re-make the PR or revert your original commits and try re-adding your changes again, more carefully this time.

**Comment by MrBobCool** [comment]
> > > > There, removed the CBT. I can't fix the 'delete all and readd' due to it most likely being causes by indentation. I've not once deleted everything and readded it during coding. Don't know what else to say.
> > > 
> > > 
> > > If it's an indentation problem then please fix the indentation problem, again, it's more so just the standard of it all than anything else. It's hard to verify your PR due to this _and_ I don't want people to start thinking it's allowed to change entire files to hide small, hidden changes. Not fixing this and having it merged like this will set that precedent.
> > 
> > 
> > There _isn't_ a way to fix this that I know of. Feel free to share a way to fix it with me. There's not indentation 'problem' it was more of a fix to add more code.
> 
> I'm not 100% sure what the issue is, therefore helping you with a fix is hard. Worst thing is you could simply just re-make the PR or revert your original commits and try re-adding your changes again, more carefully this time.

The problem is, I did add them 'carefully'. I don't see why it's doing this exactly. This could just be github acting all stupid.

**Comment by Hekzder** [comment]
> > > > > There, removed the CBT. I can't fix the 'delete all and readd' due to it most likely being causes by indentation. I've not once deleted everything and readded it during coding. Don't know what else to say.
> > > > 
> > > > 
> > > > If it's an indentation problem then please fix the indentation problem, again, it's more so just the standard of it all than anything else. It's hard to verify your PR due to this _and_ I don't want people to start thinking it's allowed to change entire files to hide small, hidden changes. Not fixing this and having it merged like this will set that precedent.
> > > 
> > > 
> > > There _isn't_ a way to fix this that I know of. Feel free to share a way to fix it with me. There's not indentation 'problem' it was more of a fix to add more code.
> > 
> > 
> > I'm not 100% sure what the issue is, therefore helping you with a fix is hard. Worst thing is you could simply just re-make the PR or revert your original commits and try re-adding your changes again, more carefully this time.
> 
> The problem is, I did add them 'carefully'. I don't see why it's doing this exactly. This could just be github acting all stupid.

I have never once seen this happen before so I am fairly certain it is not the fault of Github in this circumstance.

**Comment by MrBobCool** [comment]
Okay, I'm closing this PR. Then opening a new one. I'll try to do this as you quote; 'more carefully'.

**Pull request closed without merging**
