### PR TITLE
adds ncr rank pins, ncr QM

### PR DESCRIPTION
**Pull request by companoo**
basically #656 

-cap and lieutenant stay as they are
-qm sergeant is now just qm
-ranks are there so that in future we might be able to do some cool stuff with them

screenies: https://imgur.com/a/vUtSwct

review this shit im new

### CODE REVIEW

**Comment by UndeadNappist** [comment]
Use the BoS dogtags as a template.

**Comment by improvedname** [comment]
No wait, we have normal tags in the code, use that instead

**Comment by companoo** [comment]
this doesent change ID's it just adds an accessory onto every NCR guy showing there rank when examined, and the NCR QM role, not gonna touch ID's

**Comment by JTGSZ** [comment]
Yeah, accessories like pocket protectors/skull codpieces/medals. These can be clipped onto uniforms which is hella cool.

**Pull request closed without merging**
