### PR TITLE
Revert "Fixes role configuration"

### PR DESCRIPTION
**Pull request by improvedname**
Reverts BadDeathclaw/TG-Claw#688

### CODE REVIEW

**Comment by improvedname** [comment]
Tea is against this so im gonna speedmerge i

**Comment by improvedname** [comment]
it like you did

**Comment by improvedname** [comment]
Just because your the head coder doesn't mean your the biggus dickus on the server Rhi, tea doesn't want this so its not gonna be in period

**Comment by improvedname** [comment]
Because if this whole thing sparked up because somoene expected you to do admin stuff as devmin, which is litteraly why somoene is a devmin, then don't want to do it so you make you own snowflake title called headcoder calling it a bugfix. and speedmerging it yeah then it is void

**Comment by rhicora** [comment]
I answer ahelps all the time, this change will literally allow me to do my job again.

**Comment by improvedname** [comment]
last time somoene asked your help in tickets you litteraly said no and adminbussed shit did a restart vote and left

**Comment by rhicora** [comment]
I don't recall anything like that, feel free to send me the screenshot if someone had a bad experience with my ticket handling. As far as I'm aware hundreds of adminpms and resolutions should speak for themselves.

**Comment by Autismobirb** [comment]
@rhicora @improvedname The Git is not the place for this type of drama.
Do attempt to behave professionally, as such Rhi's role was removed for the time being due to a long conversation between the head staff and was pushed back down to just code duties, Instead of messaging me or Ren over this they have instead abused there role within our git to bring there rank back up to something that me nor Ren had agreed with or allowed.

This type of behaviour wont be looked upon in a good light, as it stands Rhi you are as follows. A head coder, this does not allow you any advanced privileges upon the server, coder rank will supply you with enough for debug and live server testing, continuing to behave in such a manner and doing as you damn well please will only lead to permanent removal of Git management.

**Comment by rhicora** [comment]
We'll discuss this with Ren when he's around. I understand why Devmin was removed, but I'm currently "Game Master" on the server and I would rather use an equivalent role which isn't labeled as an admin. If anyone else is in my position I'd want that for them too.

**Comment by Autismobirb** [comment]
See, that ain't the case, you were given game master due to Devmin, no other reason.

As such your role on server has already been pushed down on server to "coder" if you got on you would see this yourself.

**Comment by improvedname** [comment]
Yes there is a position called that, its called coder
it has all the relative permission flags you need, no need for a role with everything on it including +fun + ban, you already have everything you need for your coding duty +debug +server +VV +spawn +admin you can take that if you don't want to be a admin

**Comment by rhicora** [comment]
@Autismobirb 
image

**Comment by improvedname** [comment]
It shouldn't have been merged first place yoi can recreate a new pr when ren approves it

**Comment by rhicora** [comment]
If we don't want headcoders represented as Game Masters then this is the necessary fix for that.

**Comment by improvedname** [comment]
This isn't a fix the only real headcoder status here on github but adminstrative wise on the server any coder is just a coder

**Comment by rhicora** [comment]
I think the details of the role need to be ironed out with people who aren't the retired peanut gallery.

**Comment by Autismobirb** [comment]
For the time being instead of arguing, I would like to ask this is reverted and brought up to me and Ren when he is awake, as this was a speed merge on administrative things that are nothing to do with the coding department, else this will be taken as a account of abused permissions and someone within our coding team not coming to terms that they were removed from the Admin aspect of the team opting to instead take it into there own hands and bypassing the higher echelon of the servers management.

**Comment by rhicora** [comment]
I will know for sure that deleting the devmin role was authorized by Ren when I hear it from Ren.

**Comment by Autismobirb** [comment]
Secondly I am not happy about how quickly this was done, merged AND updated to live from the moment you were removed from Devmin despite Ryai having spoken to yourself @rhicora this behaviour isn't fitting of anyone within our team.

**Comment by JohnOxford** [comment]
theres a file for giving admins nicknames based off of ckeys.

**Comment by rhicora** [comment]
You're wildly misinformed @Autismobirb, I haven't deployed to live since yesterday.

**Comment by Autismobirb** [comment]
If I am advocating this removal of Devmin, it was passed by Ren and he would have commented on it, My apologies but none of our higher staff fly solo or do things without mine AND Ren's approval.

**Comment by rhicora** [comment]
Then I sure would've been glad to see an announcement by Ren detailing the reasons why a devmin role wasn't necessary, but I didn't. There was absolutely no communication; I was blindsided and so far it seems to be coming directly from you and Ryai. As far as I'm concerned this is weird backroom revenge for calling you out so vocally in staff chat.

**Comment by improvedname** [comment]
hhmmhm You are right

**Comment by Raze500** [comment]
Thanks for spamming my E-mail with this fight jaja.

**Pull request closed without merging**
